### ISSUE TITLE
Please remove deprecated DOM methods

### ISSUE THREAD

**Issue by sunildevadiga16** [quilljs/quill#3846] opened 2023-08-02 07:05 UTC
This is the issue when we use vue2-editor.

![image](https://github.com/quilljs/quill/assets/47885920/6fa9554e-1fad-4bdd-85e9-e71afc5843d6)

**Steps for Reproduction**

1. You just need to run your application using vue2-editor, you will see the warnings in console

**Expected behavior**: No deprecation warnings

**Actual behavior**: Seeing deprecation warnings in console

**Platforms**: Windows 11

Include browser, operating system and respective versions Google chrome, Windows 11, 

**Version**: 1.3.6

Run `Quill.version` to find out

**Comment by sunildevadiga16** [comment] 2023-08-02 07:11
@luin  and @jhchen Your help will be much appreciated. Thanks!

**Comment by luin** [comment] 2023-08-02 07:47
Hi @sunildevadiga16 👋 

Those API usages have already been removed in the develop branch and we are working actively on the next release.

**Comment by sunildevadiga16** [comment] 2023-08-02 09:27
Thanks @luin. Great to hear this.. Could you please tell the next release date?

**Comment by sunildevadiga16** [comment] 2023-08-03 06:51
Hey @luin , I am using vue2-editor package, which makes use of quill 1.3.6. And support for vue2-editor is stopped.
Requesting you to remove the deprecated APIs in 1.3.6 version also. Thanks in advance.

**Comment by luin** [comment] 2023-08-08 03:24
It's a pretty fundamental change internally so I probably won't be able to make a maintenance version for 1.x. Are they any alternatives to vue2-editor?

> Could you please tell the next release date?

I don't have an exact timeline to share but I'm working actively on it. I hope it can be released in the next 2 months.

**Comment by sunildevadiga16** [comment] 2023-08-08 09:26
> It's a pretty fundamental change internally so I probably won't be able to make a maintenance version for 1.x. Are they any alternatives to vue2-editor?
> 
> > Could you please tell the next release date?
> 
> I don't have an exact timeline to share but I'm working actively on it. I hope it can be released in the next 2 months.

There are alternatives available.. but this vue2-editor best suits our application so we are using it.

Thanks for the confirmation @luin

**Comment by leeobrum** [comment] 2023-08-28 19:06
hi, for vue3? I saw that there is a vue3-editor, similar to vue2-editor... do you know if it's good? I see it's quite outdated

**Comment by mellmers** [comment] 2024-02-01 17:17
I believe it's a duplication of #3806.

**Comment by benbro** [comment] 2024-02-20 23:23
Duplicate of https://github.com/quilljs/quill/issues/3806

**Closed by benbro** 2024-02-20 23:23 UTC
