### ISSUE TITLE
Space key doesn't work on Firefox when object created by JavaScript

### ISSUE THREAD

**Issue by screets** [quilljs/quill#1760] opened 2017-10-12 10:25 UTC
Hello guys,

It seems like Quill conflicts when you create your editor by JavaScript and then apply Quill. Especially **space key** doesn't make any affect.

Here you go: https://jsfiddle.net/jwb1rw4z/

It works on Safari and Chrome well, but **Firefox** (even in Firefox Quantum).

How can we solve this issue ?

Thanks.

**Comment by jhchen** [comment] 2017-10-16 06:09
What does created on air mean? Is this Adobe Air? It works fine on Mac + Firefox.

**Comment by screets** [comment] 2017-10-16 16:09
@jhchen 
I have updated the title. Space has no effect in Firefox/Mac when your editable object is created by JavaScript like in the example. 

I am not sure if its only my installation of general Firefox issue.

Firefox 57.0b7 (no extensions)
MacOs Sierra 10.12.6

What Firefox version are you using? Maybe i can try with that too.

**Comment by jhchen** [comment] 2017-10-23 05:08
Still works for me on Mac + Firefox. Can you provide detailed steps for reproduction? You might be doing something different that is not evident in this issue.

**Comment by jackmaw** [comment] 2017-11-28 16:04
Space key doesn't work for me too in either editor created by constructor this.quill = new Quill() or here: https://jsfiddle.net/jwb1rw4z/ 

reproduction:
type some words, press space then type another letter, the result will be:
"fizz b" --> "fizzb"

Firefox 58.0b6 (64 bit) or 57.00(64bit)
Windows 10 Pro

**Comment by jhchen** [comment] 2017-11-29 07:09
@jackmaw In your example you are not including the required Quill stylesheet: https://quilljs.com/docs/quickstart/. If you add it all is well.

**Comment by jackmaw** [comment] 2017-11-29 10:03
@jhchen thanks, for the answer  with snow theme it works.
However what if  i dont want to use stylesheets from snow theme?

In my opinion, this should be in core module,  its a little bit weird for me that i need some theme to basically have ability to write any article on firefox quantum.

**Comment by jhchen** [comment] 2017-12-15 18:34
You can see from the next link in the documentation [Download](https://quilljs.com/docs/download/) there is a quill.core.css that just has the basic styles.

**Comment by masonblier** [comment] 2018-04-12 18:57
I also hit this bug. We are not using the quill.core.css file. The critical CSS needed to fix this bug is:

```
.quill-editor {
	white-space: pre-wrap;
}
```

Very surprising this bug only happens on firefox, not chrome. It might be related with how `innerHTML` works: Chrome replaces trailing spaces with `&nbsp;`, but firefox does not.

**Comment by jhchen** [comment] 2018-04-16 03:52
Forgot to close this issue as the solution was to include the required core quill styles. I would not recommend cherry-picking just the white-space rule as you may have other issues. The quill.core.css file includes the *minimal* styles Quill recommends for normal usage.

**Closed by jhchen** 2018-04-16 03:52 UTC

**Comment by elaishane** [comment] 2021-03-19 07:13
Space key is not working in Flutter

**Comment by nonnib** [comment] 2021-11-16 12:14
I ran into this same issue despite using the required css but only when using justified align. Adding `white-space: pre-wrap;` to `.ql-align-justify` fixed it for me.

**Comment by AliReza99** [comment] 2022-08-04 08:50
for me `white-space: pre-wrap;` also did not work so I used `value.replaceAll(' ', '&nbsp;')` in onChange

**Comment by aparna-bhatt** [comment] 2023-03-06 07:54
Hello I am using ```ReactQuill``` also included ```import 'react-quill/dist/quill.snow.css';``` ```import 'react-quill/dist/quill.core.css';``` but still the space key is not working fine. 
Please help if anyone has a fix for this.
Thanks!

**Comment by akinsayo** [comment] 2023-12-12 09:56
> white-space: pre-wrap;



> I ran into this same issue despite using the required css but only when using justified align. Adding `white-space: pre-wrap;` to `.ql-align-justify` fixed it for me.

This works!
