### ISSUE TITLE
Font and font size issue when adding new line

### ISSUE THREAD

**Issue by andreisazonov** [quilljs/quill#2678] opened 2019-07-11 12:14 UTC
When I set any font-size, for example "Large", and then press "Enter" my font-size drop-down switch to "Normal"(default). But when I input in this line any symbols, font-size in drop-down again switch to those what I selected before. 
Moreover if I press "Enter" two times or more and then select other empty line, that I added, font-size will not switch to selected by me. It stay as "Normal", which was by default. Problem in that only for the last line my font-size was applied on any other it switch to the default.
The same problem with "Font" drop-down.

[Example](https://www.screencast.com/t/DETmwGGYhl)
 #1945  It looks like this issue the same. But it still not resolved.

**Expected behavior:**
When I choose font-size or font, then I press enter key , the font-size and font should keep what I chosen not changed to the default. Or it should changed to the default for all new lines, not only for last line.

**Comment by felixgeissler** [comment] 2019-12-09 09:34
I also ran into that same issue...

**Comment by garyanewsome** [comment] 2020-05-28 12:44
I found using `shift + enter` maintains the formatting while moving to a new line.

**Comment by forsureitsme** [comment] 2020-06-16 12:57
I also ran into that same issue and found a way to consistently reproduce it.

1. Open https://quilljs.com/ and go to the 3rd (full) editor example, before the `Download now` button.
2. Select the title and the first paragraph of the preloaded content and set the font size to `Huge`.
3. Go to the end of the paragraph and press Enter. The font size will turn into `Normal` in the toolbar, but as as you type anything it will turn back to `Huge` again.

**Comment by mawej1** [comment] 2020-08-31 01:52
Any updates on this?

**Comment by VaakulGoyal** [comment] 2021-03-31 10:38
Any updates on this?

**Comment by vboughner** [comment] 2021-09-08 18:58
I ran into this today. Every time you type a line in the editor that is not normal size and press return, the toolbar makes it look like the next line will be in normal size (because the size dropdown changes), but what you actually get is a continuation of the non-normal size onto the next line.

I found a bit of a hacky work-around: if you detect when you are on a new line, after a line whose size was not "normal", you can use the api to fix things up, by calling `editor.format('size', null)`. What the user types after you do that will appear in normal size.

The tricky part of figuring out when to do this. I'm doing it by watching all the editor change updates and looking for a situation when I'm at the end of the file on a new line by itself. One way I found is to watch in change updates for when `JSON.stringify(editor.getContents())` ends with `,{"insert":"\\n\\n"}]}`.  And you can determine whether the current format is not "normal" size with something like this: `const isNotNormalSize = editor.getFormat()?.size;` If both are true, then apply the `editor.format('size', null)` to fix the current format.

Not fully satisfied with that, because it doesn't detect the same situation in the middle of the file.

**Comment by ujjwalsharma98** [comment] 2023-11-16 10:19
The following code worked for me

const quill = quillRef.current && quillRef.current.getEditor();

if (quill) {
    const updatedContent = JSON.stringify(quill.getContents());
    const newLineAtEndOfContent = ',{"insert":"\\n\\n"}]}';
    const isNormalSize = !quill.getFormat().size;
    if (updatedContent.endsWith(newLineAtEndOfContent) && !isNormalSize) {
      let elList = document.querySelector(".ql-size").childNodes
      elList[0].className = 'ql-picker-label ql-active'
      elList[0].setAttribute('data-value', quill.getFormat().size)
    }
  }

**Comment by Breno-Leonardo** [comment] 2024-02-27 19:04
My solution: 

quill.root.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        const atributes = quill.editor.delta.ops[quill.editor.delta.ops.length-2].attributes;
        let size = "16px";
        if (atributes) {
          if (atributes.size) {
            size = atributes.size;
          }
        }
        const sizeSelectorOption = document.querySelector(
          `.ql-size .ql-picker-item[data-value="${size}"]`
        );
        sizeSelectorOption.click();
      }
    });

**Closed** 2024-04-17 11:37 UTC

**Comment by Mohamed3nan** [comment] 2024-11-22 05:25
this is annoying bug -_-
it's still not fixed :(
