### ISSUE TITLE
Delegate listener pattern breaks quill in (open) shadow dom

### ISSUE THREAD

**Issue by pkaske** [quilljs/quill#1811] opened 2017-11-07 19:29 UTC
I use quill inside native web components with an open shadow root and ran into problems with the `selection-change` event. It can't be catched since quill started to use a delegate event handler on `document` element (introduced in https://github.com/quilljs/quill/commit/f269276b0521bbada41ca81cd6aadece89089e17).
As the `selectionchange` event doesn't bubble through shadow roots the `selection-change` event can't be received.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/rYMPqW
2. Open dev tools console
3. Enter text into quill
4. Select some text

**Expected behavior**:
The `selection-change` event handler should log "selection was changed" to console.

**Actual behavior**:
Handler isn't fired.

**Platforms**:

https://caniuse.com/#feat=shadowdomv1

**Version**:

`>= v1.3.0`

**Comment by benbro** [comment] 2017-12-15 08:00
Is this related or duplicate of https://github.com/quilljs/quill/pull/1805 ?

**Comment by pkaske** [comment] 2017-12-15 08:19
Yes it is related. The issue is discussed in the comments and the related code change is [here](https://github.com/quilljs/quill/pull/1805/files/85afb3deda8530c57244ba3688b351dee9e7a78c#diff-a06162da0695265d8c79a70c29b6085cL10).

**Comment by benbro** [comment] 2017-12-15 09:08
So maybe it'll be better to close this issue and focus the discussion on the PR.

**Closed** 2017-12-15 10:12 UTC
