### ISSUE TITLE
Cursor moves out of view when entering newlines at the end of a document

### ISSUE THREAD

**Issue by scottjacobsen** [quilljs/quill#483] opened 2015-09-17 01:57 UTC
* Scroll to the end of document in a quill editor.
* Hit enter a few times. 

The cursor moves out of view below the bottom of the div. Typing any character other than a newline does scroll the div down.

The div should scroll down to keep the cursor in view when entering newlines at the end of a document.

**Comment by jhchen** [comment] 2015-09-18 20:10
I believe this has been fixed by #435 but with the [parchment integration](http://quilljs.com/blog/the-road-to-1-0/) in progress on the develop branch a new version of Quill with it has not shipped yet.

**Comment by jhchen** [comment] 2016-05-04 07:42
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release

**Closed by jhchen** 2016-05-04 07:42 UTC
Labels: bug, fixed-in-1.0

**Comment by justbittin** [comment] 2016-11-23 06:56
I'm actually seeing this behavior in 1.1 release.  Any 'enter key' submission will cause the cursor to eventually disappear until you press a different key.  Even starting in the middle of the document, pressing enter until it moves out of the viewable area.

I just upgraded finally from 0.20.  This did not happen in this version.

**Comment by benbro** [comment] 2016-11-23 07:29
@justbittin I can't reproduce it in the [playground](http://quilljs.com/playground/) with Chrome 54 and Firefox 50.
Please open a new issue with the requested information and how to reproduce it.

**Comment by nnenadovic** [comment] 2017-06-21 13:38
I can reproduce it in version 1.2.6, Ubuntu, Chrome 54, Firefix 54(x64)

**Comment by TheDeveloperTom** [comment] 2017-10-09 13:20
The same problem, it's really bad about the quill.

**Comment by Jagadeeswarh** [comment] 2020-08-18 14:24
I am facing this issue in the version "react-quill": "1.3.5". Any resolution?
