### ISSUE TITLE
Quill removes ul tag if add the space between ul and li

### ISSUE THREAD

**Issue by ildarnm** [quilljs/quill#2811] opened 2019-10-17 14:39 UTC
**Steps for Reproduction**

1. Visit [https://codepen.io/ildarnm/pen/zYYKBYr?editors=0010](https://codepen.io/ildarnm/pen/zYYKBYr?editors=0010)
2. If remove space between ul and li all thinks ok

**Platforms**: Chrome

**Version**: 1.3.7

**Comment by Tunlier** [comment] 2019-11-15 20:25
This is really weird. just checked in firefox dev latest on localhost and same problem.
They even don't support delta to html. So many limitations and issues I got into in just past few days.

I wish I had enough knowledge to contribute.

**Comment by Aniket-Kale** [comment] 2020-02-11 10:05
I am also facing the same issue. @ildarnm and @Tunlier Did you find any solution or workaround for this issue?

**Comment by Tunlier** [comment] 2020-02-12 09:25
Sadly no.

**Comment by HJBDev** [comment] 2020-07-14 14:15
In my case, I was inserting existing html using dangerouslypastehtml (I know you shouldn't really do this.)

But my workaround was like this:
`quill.clipboard.dangerouslyPasteHTML(0, this.html.replace(/\s+/g,' '));`

`this.html` being my existing HTML.

**Comment by Fireprufe15** [comment] 2022-03-16 07:19
For now, I have written a regex to replace the spaces between list tags

`
editor.root.innerHTML = "Hello<ul> <li>world!</li></ul>" .replace(/(<ul>|<ol>|<\/li>)(?:[\s]+)(<li>|<\/ul>|<\/ol>)/g, '$1$2');
`

**Comment by sufiyan-e-bot7** [comment] 2022-04-06 10:42
Another working example with the issue. 
https://codesandbox.io/s/quill-blot-formatter-demo-forked-30dkkm?file=/src/index.js

**Comment by vaheqelyan** [comment] 2022-12-20 10:14
+1

**Closed** 2024-04-17 11:13 UTC

**Comment by Elevista** [comment] 2025-08-26 06:19
```ts
class Ul extends Block {
  static blotName = 'ul'
  static tagName = 'LI'
  static register() {
    Quill.register(UlContainer, true)
  }
}
class UlContainer extends Container {
  static blotName = 'ulList'
  static tagName = 'UL'
  static allowedChildren = [Ul]
}
Ul.requiredContainer = UlContainer
class Ol extends Block {
  static blotName = 'ol'
  static tagName = 'LI'
  static className = 'ol' // This is necessary!!
  static register() {
    Quill.register(OlContainer, true)
  }
}

class OlContainer extends Container {
  static blotName = 'olList'
  static tagName = 'OL'
  static allowedChildren = [Ol]
}
Ol.requiredContainer = OlContainer
Quill.register(`formats/ul`, Ul, true)
Quill.register(`formats/ol`, Ol, true)

// quill.format('ul', true)
// quill.format('ol', true)
```

[https://github.com/slab/parchment/blob/3d0b71c95c056a3fd595e7a22f7ecd221f104268/src/registry.ts\#L86-L96](https://github.com/slab/parchment/blob/3d0b71c95c056a3fd595e7a22f7ecd221f104268/src/registry.ts#L86-L96)

After reviewing the source code, it appears that by design, multiple blot types cannot be matched to the same `li` tag. This is a very disappointing structure.
Therefore, to distinguish between `li` elements within `ul` and `ol`, it's necessary to add a `className` as a differentiator, even if it might not seem essential at first.


```ts
import Clipboard from 'quill/modules/clipboard'
import normalizeExternalHTML from 'quill/modules/normalizeExternalHTML'

Object.assign(Clipboard.prototype, {
  normalizeHTML: (doc: Document) => {
    normalizeExternalHTML(doc);
    doc.body.querySelectorAll('ol>li:not(.ol)').forEach(li => li.classList.add('ol'));
  }
})
```
migrate from other editor
