### ISSUE TITLE
There are errors when using Chinese input methods in versions above Quill 2.0

### ISSUE THREAD

**Issue by 723386252** [quilljs/quill#3969] opened 2024-01-24 12:10 UTC
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

I am using quill-2.0.0@beta.1 Version, I found a bug where when the editor has no content, I use Chinese input method for input, which results in unsuccessful input and inability to backspace

https://github.com/quilljs/quill/assets/67086243/fd189118-5636-4ae8-b884-50bc7e9dc658

**Platforms**:
ios

**Version**: 
2.0.0-beta.1

**Comment by luin** [comment] 2024-01-24 13:48
Can you try if you could reproduce the issue on https://v2.quilljs.com/standalone/full. It works for me correctly (though the placeholder didn't get cleared during IME composition but would consider it as a separate issue)

**Comment by 723386252** [comment] 2024-01-24 13:56
On the website you provided, I can also reproduce the issue under the following conditions: 1. Chinese input method 2. Empty contenthttps://github.com/quilljs/quill/assets/67086243/945ce825-768f-4b49-a7fd-a252ef040d92

**Comment by luin** [comment] 2024-01-24 14:01
What's the Chinese IME did you use? Would you reproduce the issue with the built-in Chinese IME?


https://github.com/quilljs/quill/assets/635902/a47c3f87-b053-4b91-a3aa-d8775fce4e21

**Comment by 723386252** [comment] 2024-01-24 14:09
Of course, I also used the built-in Chinese input method in iOS for testing, and whether it was a Chinese nine key or full keyboard, I was able to reproduce this issue. Of course, this bug is not mandatory, it often occurs, and sometimes it is normal

https://github.com/quilljs/quill/assets/67086243/d264a8bf-242d-4db7-8bf5-f8cfc1c69ad2

**Comment by 723386252** [comment] 2024-01-24 14:29
My iOS version is also 17.2.1, perhaps you can try to reproduce this issue using WeType（wechat input method）

**Comment by 723386252** [comment] 2024-01-24 14:33
Strangely, in the MacOS system, I am unable to reproduce this issue and can only replicate it on mobile devices

**Comment by 723386252** [comment] 2024-01-24 14:38
In my device, it seems that all input methods that can trigger the compose state will encounter this bug

https://github.com/quilljs/quill/assets/67086243/d37d10b2-1644-439a-80da-b8a53c690905

**Comment by luin** [comment] 2024-01-24 14:48
Thanks for the details. I tried WeType and still didn't reproduce the issue 🤔. Not sure if it's related to any settings

**Comment by 723386252** [comment] 2024-01-24 15:03
I tried to input on the iPad, and the same bug appeared. Perhaps it is related to the Chinese system?

https://github.com/quilljs/quill/assets/67086243/96eaaeac-2a1a-41de-bcb8-af4ad2d74144

**Comment by luin** [comment] 2024-01-24 15:15
I did switch to Chinese for the system language but it still works on my side. Probably try disabling Safari extensions or running in private mode?

**Comment by 723386252** [comment] 2024-01-24 15:23
I tried using Chrome Mobile browser for testing and found that the issue disappeared. Now it can be confirmed that this is related to Safari browser. I have disabled all extensions and the bug still persists. Tomorrow, I will perform breakpoint debugging on the code and try to find the cause of the bug myself

**Comment by 723386252** [comment] 2024-01-25 01:22
![image](https://github.com/quilljs/quill/assets/67086243/0b4fef05-3210-4445-bcc5-261d134f7e9c)
In the scroll-before-update and scroll-update events, two key MutationRecords are missing, which contain the newly added # text element, while in the scroll optimize event, the content is complete

**Comment by luin** [comment] 2024-01-25 06:25
Thanks for the info. I've reproduced the issue and started looking at it.

**Comment by luin** [comment] 2024-01-25 13:01
@723386252 Can you try `npm install quill@0.0.0-experimental-b9ebd32ba-20240125` and see if the PR fixes the issue?

**Comment by 723386252** [comment] 2024-01-26 08:44
@luin Perfect, the problem has been resolved. I have another suggestion, which is to hide the placeholder during Chinese input when the content is empty

**Comment by luin** [comment] 2024-01-27 14:14
It should be easy to implement on userland (by listening to compositionstart event and clear the placeholder). Not sure if we should support it in Quill core. I'm thinking about more the placeholder out of the core actually.

Closing this. Feel free to create a new ticket if you think the placeholder is necessary.

**Closed by luin** 2024-01-27 14:14 UTC
Labels: bug, safari
