### ISSUE TITLE
Quill generates semantically wrong HTML for lists

### ISSUE THREAD

**Issue by JurajKavka** [quilljs/quill#3463] opened 2021-10-17 16:23 UTC
This issue references #979 

I opened this because I would like to know if issue with lists is solvable in Quill (Parchment) in WYSIWYG manner. Main problem is that Quill generates semantically wrong HTML witch leads to incorrect numbering of nested levels ... 

If I understand correctly, Quill does not support nesting block blots and without that, lists will not work as they should. Is there any plans to do support for nesting blocks and solve this issue?

**Steps for Reproduction**

1. Visit quilljs.com
2. In demo editor, try to create numbered list with at least two main levels and their nested levels

**Expected behavior**:
Numbering of nested levels will be resetted for each parent level

**Actual behavior**:
Numbering of nested levels just continues ...

**Platforms**:
platform independent

**Version**:
all versions

**Comment by Naskalin** [comment] 2021-11-05 15:58
Hm, i have ok for Win 10, Chrome 95.0.4638.69
![image](https://user-images.githubusercontent.com/8067967/140540085-fa942305-1a79-4fbf-80fd-fb52ecea6a0f.png)

can you repeat this error now?

**Comment by JurajKavka** [comment] 2021-12-16 10:08
Firefox on Linux

![image](https://user-images.githubusercontent.com/31443024/146351684-66a25707-1ed1-49b9-8b91-75e9fd3f61f2.png)

**Comment by duhaime** [comment] 2022-01-18 12:04
@JurajKavka since this issue is a duplicate of #979, I think we should close this issue and focus attention on #979 instead...

**Comment by benbro** [comment] 2024-02-22 10:08
Duplicate of https://github.com/quilljs/quill/issues/979

**Closed by benbro** 2024-02-22 10:08 UTC
