### ISSUE TITLE
At.js and inserting HTML

### ISSUE THREAD

**Issue by mkallies** [quilljs/quill#1557] opened 2017-06-29 18:44 UTC
When typing an @mention using Quill and At.js, I've noticed in Quill that the HTML reads `<p>@mention</p>`.  I believe At.js is expecting to see something along the lines of `<span class='atwho-query'>@mention</span>` in order to apply it's dropdown menu in the correct position as well as the cursor position.  

Has anyone found a way to remedy this?

**Platforms**:

Chrome 59, mac

**Version**:

1.2.6

**Comment by mkallies** [comment] 2017-06-30 18:28
This code seems to alleviate the issues.  At.js is able to insert with the span and the class.  Only problem is after insertion, the cursor jumps to the beginning or the end of the span depending on which direction you're moving with the arrow keys.

Pressing backspace deletes the mention.

```
    const Parchment = Quill.import('parchment');
    const Query = new Parchment.Attributor.Class('custom', 'atwho', { scope: 
        Parchment.Scope.INLINE_BLOT, whitelist: ['query', 'inserted'] });
    Quill.register(Query, true);
```

**Comment by jhchen** [comment] 2017-07-16 21:46
Seems like a duplicate of #945

**Closed by jhchen** 2017-07-16 21:46 UTC
