### ISSUE TITLE
Font style is not preserved on copy paste

### ISSUE THREAD

**Issue by amitguptagwl** [quilljs/quill#1200] opened 2016-12-19 10:22 UTC
When I copy paste some HTML or some text from one place to another place within the editor, it applies default font style.

1. open [document](https://docs.google.com/document/d/1nsto_2JcJ3BrW5a5DIajEkUn9_RnYuz_F0GRU2HP_3g/edit?usp=sharing)
2. copy 1st paragraph and unordered list.
3. goto quilljs.com
4. paste in editor. It looses font style for text in unordered list.
5. apply some font style to this text again.
6. cut the whole text and paste.
7. again it looses the font style.

**Comment by jhchen** [comment] 2016-12-23 06:35
To clarify this is just the inline code style not being preserved? The link and bullet is being pasted correctly. I also cannot reproduce step 5-7. Some specifics may help.

**Comment by amitguptagwl** [comment] 2016-12-23 07:34
I have recorded this video. Have a look. If it is not clear, I'll upload the video and share the link.
As you can see in the recording
1. it lost the font style for `stubbydb init <workspace-name >` and other commands text
2. When I tried to select the font to give new font style, selection disappear (which was working when I tried few days back). However, eventually I realised that it disappears but still working. So I gave new font style.
3. Ctrl+A --> Ctrl+X --> Ctrl+V
4. Again font style lost for the same text.


![Recording](http://i.giphy.com/3o6ZtevG5FXHjPNKIo.gif)

**Comment by jhchen** [comment] 2016-12-23 08:52
Step 5-7 is a duplicate of your own issue #1201.

For 1-4, the issue is you are trying to paste a font Courier New that has not been added to Quill. If you want to pick the "closest" font, you can create a [clipboard matcher](http://quilljs.com/docs/modules/clipboard/) to add this logic. Otherwise there is no way in JS to figure out what fonts are visually "close" without custom logic.

**Closed by jhchen** 2016-12-23 08:52 UTC
Labels: needs clarification, triage

**Comment by amitguptagwl** [comment] 2016-12-23 09:48
No these are 2 different issues. In this issue font style is not preserved after copy paste (from the editor to the editor). While in the issue [#1201](https://github.com/quilljs/quill/issues/1201), font style is preserved but it is automatically apply on more text after paste. I'll create the video of that separately and put it in comment.
