### ISSUE TITLE
Quill 1.1.8+ does not react to input properly

### ISSUE THREAD

**Issue by ergo** [quilljs/quill#1253] opened 2017-01-10 11:19 UTC
Hello,
I've upgraded qulljs from 1.1.7 to 1.1.9 and input handling seems to be somewhat broken.

**Steps for Reproduction**

1. Write some text, press enter
2. Try to write some other text

**Expected behavior**: Some more letters added to the document
**Actual behavior**: Nothing is printed, delta is not updated. It "looks" like lost focus, because after clicking the editor one can type again until enter is pressed again. However, it is important to note that arrow keys can control caret just fine and enter keypress inserts newline - user just can't type the text. The problem only occurs on firefox, chromium behavior is correct.

**Platforms**: Linux Ubuntu 16.04,  Firefox 50.1.0

**Version**: versions 1.1.8+ are affected

Version 1.1.7 works fine on both browsers I tested.

**Comment by benbro** [comment] 2017-01-10 12:12
I can't reproduce. Works fine for me.
Do you see the issue in the [codepen example](http://quilljs.com/playground/)?

**Comment by ergo** [comment] 2017-01-10 19:15
No, I can't reproduce it in the codepen either, happens in my application though - I'll try to provide a test case, I'm not sure what's causing it yet.

Something must be different between versions since 1.1.7 works fine for me.

**Comment by cutteroid** [comment] 2017-01-11 10:45
I'm getting some kind of this issue too but with backspace. An actual behavior is same - editor is focused (caret blinks) but no response on character keys until user clicks editor body.

Its reproducible for me on [playground](http://quilljs.com/playground/#autosave) in Firefox on Windows and OSX:

1. select all editor content (some formatted content should be present in editor)
2. hit backspace
3. try to type something
4. notice that nothing is printed

**Comment by ergo** [comment] 2017-01-11 10:47
Yup, I can replicate this too, what I'm seeing in my application looks the same, except happens also on enter.

**Comment by rikh42** [comment] 2017-01-11 19:16
Do you have any custom key bindings?

**Comment by ergo** [comment] 2017-01-11 19:38
Not that I recall.

**Comment by jhchen** [comment] 2017-01-21 09:39
This looks like a duplicate of #1254. Following @cutteroid 's instructions on the most recent 1.2.0 does not exhibit this bug.

**Closed by jhchen** 2017-01-21 09:39 UTC

**Comment by ergo** [comment] 2017-01-21 09:47
Confirmed, looks like 1.2.0 fixes this. Thank you for all the great work.
