### ISSUE TITLE
Cannot read property 'emitter' of undefined

### ISSUE THREAD

**Issue by billyshena** [quilljs/quill#2309] opened 2018-09-13 16:34 UTC
Hello guys ! I am trying to replace all my `<li></li>` tags by `<p></p>`.

How I did:

1- Importing the ListItem
let ListItem = Quill.import('formats/list/item')

2- Applying changes
ListItem.tagName = 'P'
ListItem.blotName = 'list-item'

3- Registration
Quill.register(ListItem)

When I type in the editor, the `<li>` tags are correctly replaced by `<p>` tags but I have this error in my console output:
<img width="480" alt="capture d ecran 2018-09-13 a 18 33 57" src="https://user-images.githubusercontent.com/6057397/45502192-a1537480-b783-11e8-92b3-cba616fcc93f.png">

Any ideas ? 

Best,

**Comment by benbro** [comment] 2018-09-13 16:46
Can we close this if it's a duplicate of https://github.com/quilljs/quill/issues/1237?

**Closed** 2018-09-15 01:04 UTC
