### ISSUE TITLE
Quill can't determine line color after being destroyed and reinitialized

### ISSUE THREAD

**Issue by jakedeichert** [quilljs/quill#527] opened 2015-11-17 22:26 UTC
When you type in a certain color, Quill uses that same color when you make a new line. However, if you destroy Quill and reinitialize it, it won't be able to determine line colors anymore as you type.

Check out this demo to see what I mean: https://jsfiddle.net/jakevenngage/n6ee9n44/

And here's a screenshot of the steps to reproduce in the demo...

1. Press the Destroy and Init button. 
2. Highlight some text, change the color to red.
3. Type a little, then make a new line and type more. It should be red, but it's black.

![quill color issue](https://cloud.githubusercontent.com/assets/1631044/11226741/d058541e-8d4f-11e5-89e8-e011fe53e4aa.png)

Any thoughts?

**Comment by jhchen** [comment] 2015-11-18 00:19
Why should this state be preserved? You are destroying the editor after all. If the state was left behind that could be considered a memory leak bug in `destroy()`.

**Comment by jakedeichert** [comment] 2015-11-18 00:45
Not sure if you understand what I mean. When you create the first instance of Quill, it can make a new line using the same "current" color that the line before had.

When you destroy Quill and then create a new Quill, the new Quill cannot make new lines using the current color the cursor is on.

So the new Quill has lost a feature that the first instantiation of Quill has the ability to determine.

Do you understand what I mean?

**Comment by jakedeichert** [comment] 2015-11-18 01:06
I updated my issue comment to use "determine" instead of "remember" (bad word choice). This issue doesn't have anything to do with state/remembering anything.

**Comment by jakedeichert** [comment] 2015-11-18 17:16
Here's better proof.

In the first screenshot you can see my cursor is on the new line and my color is currently set to red.

In the second screenshot, as soon as I type anything, the color automatically changes from red to black.

This is the bug I'm trying to describe to you.

If you ever destroy your first instantiation of Quill and then create a new Quill, every following instance of Quill is affected by this bug.

![test2](https://cloud.githubusercontent.com/assets/1631044/11248182/c3aa97a6-8ded-11e5-8e1f-6758d68dc6c2.png)

**Comment by jhchen** [comment] 2015-11-19 00:02
Thanks for the clarification. I misunderstood the first time.

**Comment by jhchen** [comment] 2016-05-12 08:31
This looks like it's been fixed in the 1.0 beta preview: http://jsfiddle.net/f3jx8ywp/1/. There's no longer a delete but removing the container and adding it is the closest to it.

**Closed by jhchen** 2016-05-12 08:31 UTC
Labels: all-browsers, bug

**Comment by jakedeichert** [comment] 2016-05-12 14:23
@jhchen Yes, that works great now. I'm excited for 1.0!

However, just clarifying whether this is expected: My cursor is on the red character but red is not showing in the dropdown. If I move my cursor onto black text, black shows in the dropdown. I'm assuming red should show in the dropdown.

![screen shot 2016-05-12 at 10 21 58 am](https://cloud.githubusercontent.com/assets/1631044/15217849/626884ee-182b-11e6-82d3-1255e1caa09f.png)

**Comment by jhchen** [comment] 2016-05-12 18:00
I got lazy with the example and didn't make the dropdown work fully. Here's how it should be: http://jsfiddle.net/f3jx8ywp/2/. The problem is the color needs to be an exact match with the option value and some browsers insert spaces inside the color tuple. Quill's themes take care of this or you can also use classes in 1.0 to represent colors.
