### ISSUE TITLE
Scroll position is lost after pasting (with `scrollingContainer: null`)

### ISSUE THREAD

**Issue by dcsaszar** [quilljs/quill#2027] opened 2018-03-19 13:10 UTC
**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/geLExY
2. Scroll down a bit
3. Paste some text

**Expected behavior**:

Scroll position is unchanged, or keeps the text cursor visible.

**Actual behavior**:

The scroll position is at the top.
The text input cursor is not visible.

**Platforms**:

OSX High Sierra Chrome 65.0.3325.162

**Version**:

//cdn.quilljs.com/1.3.6/quill.js

**Comment by paulkoanui** [comment] 2018-04-19 17:41
Also experiencing this issue using the following version through bower:

https://github.com/quilljs/quill/releases/download/v1.3.6/quill.tar.gz

**Comment by zhangcaidie** [comment] 2018-07-04 13:08
I'm experiencing this issue too, it bothers me for two days, can somebody solve this problem?

**Comment by geeosh** [comment] 2018-08-24 14:09
Yes, this issue still exists -- even after https://github.com/quilljs/quill/commit/f79705ca2dac6ed27015a00d8594ef11986bb0a7 was applied.

**Comment by askosh** [comment] 2019-03-24 12:48
Can confirm, still an issue

**Comment by clementmas** [comment] 2019-04-25 04:11
Seems like a duplicate of #1374 

This option fixed my scroll jump issue but it still flickers:
`scrollingContainer: document.documentElement`

**Comment by 1002237913** [comment] 2020-03-02 06:26
This is also a good solution
```javascript
   function findEditorScrollContainer(quill) {
      let el = quill.root;
      while (el) {
        if (el.scrollTop > 0) {
          break;
        }
        el = el.parentElement;
      }
      return el;
    }

     quill.on('editor-change', (type, delta, oldDelta, source) => {
          quill.scrollingContainer = findEditorScrollContainer(); // Solve the problem of scrolling to the top when pasting
         // your others code
       
     });
```

**Comment by Filipeue** [comment] 2020-03-18 18:31
This solution worked perfect in my case:
I  cannot just set `scrollingContainer: document.documentElement` because i don't know where and how my editor will be used. So when creating Quill instance I try to find nearest scrolling element.
```ts
export function getScrollParent(node: HTMLElement | null): HTMLElement {
  if (!node) {
    return document.documentElement;
  }

  const overflowY =
    (node instanceof HTMLElement && window.getComputedStyle(node).overflowY) ||
    '';
  const isScrollable = !(
    overflowY.includes('hidden') || overflowY.includes('visible')
  );

  if (isScrollable && node.scrollHeight >= node.clientHeight) {
    return node;
  }

  return getScrollParent(node.parentNode as HTMLElement | null);
}
```
and use it like this when creating Quill instance (react+ts):
```tsx
    quill.current = new Quill(editorEl.current, {
      scrollingContainer: getScrollParent(editorEl.current),
    });
```

**Comment by lakindu2002** [comment] 2022-01-05 15:52
the issue is still there in 2021. any fixes?

**Comment by dirkdirk** [comment] 2022-06-01 22:38
the issue is still there in 2022. any fixes?

**Comment by dirkdirk** [comment] 2022-06-02 22:35
> @lakindu2002 @dirkdirk Is the solution I provided above inadequate for your use case?

@Filipeue 

When I have Chrome's dev tools open the given solution does not work, but if dev tools is closed it works just fine.  

Why would that be?

**Comment by akshayknz** [comment] 2022-12-02 06:39
None of the solutions worked for me ☹

**Comment by TOLU-MICH** [comment] 2024-04-17 00:03
`var quill = new Quill('#editor', { 
  modules: { toolbar: toolbarOptions },
    theme: 'snow',
    scrollingContainer: 'body'
});`
This worked for me

**Closed** 2024-04-17 11:35 UTC
Labels: bug:functionality, 1.x only
