### ISSUE TITLE
how to reset dropdown handlers for dynamic quill initialization

### ISSUE THREAD

**Issue by grimace** [quilljs/quill#2724] opened 2019-08-17 11:46 UTC
I'm trying to toggle quill on and off for independent edit areas on page.  I have a static area for the toolbar which should work for what ever area the user is editing at any time.  It works for the most part, except that dropdown handlers do not get re-populated.  

Bold, Underline, Clear, Italic seem to work well, but I can't get dropdowns to work correctly (after the initial edit area),  like font and font-size.

I've built a code pen which demonstrates.  
[codepen example](https://codepen.io/grimace-the-bashful/pen/VwZjabo)
If you first select an area, you can highlight text and change fonts as well as changing font size.  Bold, Underline, Italic work as well.

When I leave an area,  by clicking on a different div,  I reset quill and point it to the new area.  I can then highlight text and Bold, Underline, Italic, but font and font-size dropdown do not work.

I'm wondering if there is a way to programmatically reset the dropdown handlers.

**Expected behavior**:
I'd like dropdowns to work as well as single click edits such as Bold and Underline

**Actual behavior**:
dropdowns do not work with newly selected div/text

**Platforms**:
chrome, safari, OS/X Mojave

**Version**:
quill version 1.3.6

**Comment by benbro** [comment] 2019-08-22 22:25
Duplicate of https://github.com/quilljs/quill/issues/633

**Closed by benbro** 2019-08-22 22:25 UTC
