### ISSUE TITLE
Cursor is at the wrong index after text is inserted programmatically

### ISSUE THREAD

**Issue by e7hz3r0** [quilljs/quill#1301] opened 2017-02-03 02:33 UTC
When inserting text via the API, the cursor doesn't end up at the right index.

**Steps for Reproduction**

1. Visit [jsfiddle](https://jsfiddle.net/h08dp6ke/)
2. Select the text field 
3. Type 't' followed by a space.
4. The program replaces the 't' with 'the' and preserves the trailing space

**Expected behavior**:
The cursor should be at index 4, after the word 'the' and the trailing space.

**Actual behavior**:
The cursor ends up at index 2.

**Platforms**:
* Chrome 55
* MacOS 10.12.3

**Version**:
Quill version 1.2.0

**Comment by jhchen** [comment] 2017-02-10 09:13
The issue is you are changing the editor text inside the text-change handler. In general you should not trigger an event in the handler for that event. There's no infinite loop in this case but because function calls are stacks the restoration at the end is going to be the oldest. Unless you see a much simpler solution on Quill's side, it's a bit complex and out of scope for Quill to detect and guard against this practice.

**Closed by jhchen** 2017-02-10 09:13 UTC
