### ISSUE TITLE
Status of quill

### ISSUE THREAD

**Issue by denjaland** [quilljs/quill#2619] opened 2019-05-16 15:31 UTC
Hi,

Sorry about posting this here, but I was whecking out quill js and evaluating whether we are going to use it in our project.  But even though I see a lot of checkins still occuring, it seems to be a while since a new version has been released.

Also, he blog's latest post dates back from september 2017, so I was wondering whether this library is still actively maintained (the number of checkins confirm that, but it appears sstrange that there has been no releases for quite a while...)

If anyone could direct me to some more info on "the status of quill", I'd be very thankful.
Again - apologies for abusing the issues tracker for this question.

**Comment by godenji** [comment] 2019-05-16 23:35
Most likely everyone that wants to use 2.0 features is depending on latest dev release directly. We're using *ngx-quill*, which depends on latest stable 1.x release so benefit from none of the 2.0 dev branch features :\

Would be great if a 2.0 release were made in the not too distant future; has been a long time since a new release has been published...

**Comment by sprasad02** [comment] 2019-05-17 10:48
The table support in 2.0 is amazing and it would be great if this could be rolled out as prod release.

**Comment by denjaland** [comment] 2019-05-17 11:02
Yes well, since we always try to stick to releases that we pull in through npm for any third party library, it made us doubt to going down this path, because the latest release is 14 months old.

It looks as if quilljs is really good, and would love to incorporate it into our UI, but the fact that there are new releases nor new blogposts made us doubt about whether this is the best choice we can make...

**Comment by xiegeo** [comment] 2019-05-18 17:10
I'm here for the same reasons. If 2.0 is close to stable, I would rather just start using it now, but v1 also looks good enough for my needs. Is there any project road map available for 2.0 and documentation for how to upgrade from v1 to v2?

**Comment by alecgibson** [comment] 2019-05-22 10:40
There's a (WIP) guide on the `develop` branch: https://github.com/quilljs/quill/blob/develop/docs/guides/upgrading-to-2-0.md

**Comment by shyamal890** [comment] 2019-05-29 04:27
Yet if you look at the recent commits, in the last 7 days there haven't been any commits in last month only one commit was made. 

I wonder if we are ever going to see 2.0 released

**Comment by RobAley** [comment] 2019-06-02 10:53
I've been using v1 for a couple of years, but I'm also considering jumping ship to another editor. Not because v2 is taking a while, but because of the lack of public communication around it, which gives pause for thought over the future of the project. @jchen are there any updates about progress or the project in general you can share with us to assuage these concearns?

**Comment by arggh** [comment] 2019-06-02 11:27
> jumping ship to another editor.

@RobAley what would that other editor happen to be? Last time I checked, QuillJS was the only one capable of producing consistent content across different browsers, rest of them were flawed by design. It was a while ago though.

**Comment by RobAley** [comment] 2019-06-02 11:33
I've not chosen one yet, I'm still hoping quill v2 can pull it out of the bag, so to speak. However cross browser support isnt a worry for me as it's for an electron based app, so there's quite a number of alternatives to choose from. Would rather stick with Quill if i can be more confident of it's future.

**Comment by alecgibson** [comment] 2019-06-02 16:37
For what it's worth, I've recently had a couple of pull requests reviewed and merged pretty quickly recently, so I think this is still under pretty active development.

**Comment by denjaland** [comment] 2019-06-02 16:56
Yes - that’s the confusing part - There are MANY commits, but no releases being tagged.  Even the most recent 1.x release is quite old, which makes me wonder if there ar no bugs there that are worth a new release.  I know we can pull in from github master, but we follow the policy of only pulling in releases...

**Comment by DokaRus** [comment] 2019-06-05 18:00
Hey, @jhchen could you clarify the current state of the Quill?

**Comment by benjismith** [comment] 2019-06-08 21:18
Yeah, I'd love to see a blog post about the evolving philosophy behind the 2.0 design, and a rough timeline of the progress... My product is heavily dependent upon Quill, and there are some limitations of the 1.0 architecture that I'm keen to solve.

**Comment by heruan** [comment] 2019-06-09 13:15
Even the absence of a maintainer's comment on this one-month-old issue is a bad sign… The current status speaks for itself: few recent commits, lots of open issues and PRs, no new releases. I understand open-source is hard to maintain, but at least communication should be the top priority.

**Comment by denjaland** [comment] 2019-06-09 14:45
@heruan in a sense that ansence answered my question...

**Comment by alexgurrola** [comment] 2019-06-10 21:33
It does look as though contributions have slowed in [graphs/contributors](https://github.com/quilljs/quill/graphs/contributors), but that could simply mean that @jhchen needs more maintainers to keep it going.

**Comment by denjaland** [comment] 2019-06-11 05:20
I agree, but as a newcomer checking out quill, I’m just trying tobunderstand the status.  If @jhchen would confirm that that’s the case, then at least there would be an update.  Currently, I have no clue whether quill IS still active or not.

**Comment by godenji** [comment] 2019-06-11 05:34
That none of the maintainers have chimed in here speaks volumes; that, or it's simply easier to ignore the unwashed masses and proceed to use Quill as they see fit, with the community in mind or not.

Saying that, it would be great to hear something definitive as I prefer Quill to, for example, TinyMCE, which I'll have to go back to if this project has been abandoned.

**Comment by padraigfl** [comment] 2019-11-04 14:05
How often does a project have this little communication about a new version for this long and actually see the new version released? I'd be stunned if version 2 ever comes out at this stage.

If we could aggregate whatever issues it has, what breaking changes are involved (I've witnessed very few, but I assume they're there?), etc, then at least someone might feel comfortable picking up the project

**Comment by Gladskih** [comment] 2019-11-21 22:35
I regret to have added dependency from dead Quill project into my app earlier. You reading this comment do not repeat my mistake

**Comment by alexgurrola** [comment] 2019-11-22 19:14
@Gladskih: I think @jhchen is likely overtasked with how many issues are popping up here, as there are still commits actively happening in this repository.

**Comment by gumatias** [comment] 2020-01-22 13:39
@Gladskih what would you recommend instead?

**Comment by Gladskih** [comment] 2020-01-22 21:54
@gumatias Maybe https://tiptap.scrumpy.io/

**Comment by padraigfl** [comment] 2020-01-23 11:03
Yeah Tiptap is great! Envious of all the Vue developers to get to use it... As far as I'm aware it's a fairly straight implementation of ProseMirror (just way more advanced than any of the ones for React)?

**Comment by gumatias** [comment] 2020-01-23 15:28
Thanks all! It sounds like you're more informed than I am on this. I wondering if QuillJS is still one of top options we have right now when it comes to feature set availability?

I'm looking for something that can hopefully work on React and have modules/plugins available such as:
1. Load/Paste Word document (and hopefully keep formatting and things such as tables)
2. Compare text versions (for redlining)
3. Add comment on the text
4. Add custom fields or required inputs within text
and a few more along these lines of Google Docs behaviors

**Comment by bravik** [comment] 2020-01-24 02:35
quill is obviously dead.
The only issue with <p> tag instead of <br> for newlines makes it a pain!
Multi-level lists and other things.... ah...
I'm also looking for an alternative.

Tiptap looks nice at first glance but then it has it's own down sides. For example try to change font-size or text-color..

So I guess you should be really specific on what features you need before choosing the editor.

**Comment by padraigfl** [comment] 2020-01-24 14:06
Oh yeah, all of them have downsides. I even notice Google Docs has some mildly confusing handling of things with tables, presumably to safeguard against bugs. Bizarre that tiptap doesn't allow colors but the inline-level font size thing seems to be a general issue.

Another factor to consider is whether you need a fully open source option; CKEditor or TinyMCE might meet your needs, at the very least you'd be dealing with an editor that roughly meets the standards a user might realistically expect as far as features are concerned.



A huge issue with all of this stuff is how old the search results are for it. I just looked up CKEditor vs TinyMCE and the top result was from 2010! I plan on updating Quill's documentation in this regard a bit whenever I can find the time as it's ~3 years old now (making it much newer than most the results google is giving me right now).

**Comment by himynameistimli** [comment] 2020-02-05 04:46
Has anyone tried migrating from Quill to [Slate](https://github.com/ianstormtaylor/slate)?

I saw this post dated a few years back but it seems similar to our issues. I'm just worried about all of our saved documents being properly rendered via Slate.

https://medium.com/the-lead/why-we-moved-from-quill-to-slate-94f42aa54fec

**Comment by padraigfl** [comment] 2020-02-05 11:56
I don't think Slate has been around long enough to warrant a move tbh, by its own admission it's in beta and I haven't seen much to suggest that it's a drastic improvement. If it were a new project maybe it'd be worth a try, but to undergo the hassle of moving everything over it seems not worth the hassle.

**Comment by gumatias** [comment] 2020-02-06 17:48
Appreciate the thoughts @padraigfl ! Although not entirely free for my purposes, CKEditor seems to have some neat features I would need to build for other open source editors otherwise. I'll keep watching this thread in case something else pops up. thanks!

**Comment by oliverw** [comment] 2020-10-07 17:24
> Has anyone tried migrating from Quill to [Slate](https://github.com/ianstormtaylor/slate)?
> 
> I saw this post dated a few years back but it seems similar to our issues. I'm just worried about all of our saved documents being properly rendered via Slate.
> 
> https://medium.com/the-lead/why-we-moved-from-quill-to-slate-94f42aa54fec

Judging by its repo, Slate appears to be just as dead.

**Comment by padraigfl** [comment] 2020-10-25 16:10
Yep, the issue isn't Quill or Slate, it's just very hard to do this kind of thing and users having been raised on Microsoft Word have extremely high expectations of what can be easily added in.

Of the open source options ProseMirror is by far the one most likely the be capable of doing any particular thing and imo it has the most readable data but the real focus should be on reducing expectations as the cost of maintaining any additional features on a rich text editor is gonna be gigantic. If you absolutely need those features, it seems smarter to go with a paid option than potentially have multiple developers being repeatedly pulled into fixing bugs.

Said it before in another issue I'm sure, but Quill's biggest issue is the total ambiguity of v2. If v2 was outright cancelled and the focus was instead on resolving issues with v1 and clearly acknowledging its limitations instead of claiming easy expandability then I think it'd be in a pretty good place., it is a pretty neat tool for small use cases

**Comment by kovalforpublic** [comment] 2022-07-14 02:06
So, the project is dead? Latest verson is 1.3.7

**Comment by denjaland** [comment] 2022-07-14 11:17
I can recommend tiptap.

**Comment by kovalforpublic** [comment] 2022-07-14 12:24
@brooksdra I'm thinking about **TinyMCE**, although not sure about mentions/tags support. Seems to be so that there's a module for that, but it's also not well maintained. I'm starting to believe there's no decent open source WYSIWIG editor out there (with customisation and enough different modules), only the proprietary ones. Not sure I'm ready to pay ~$1000 per year for a pet project. Such a pity.

**Comment by padraigfl** [comment] 2022-07-14 12:46
@brooksdra what's the feature? I can probably give you some idea of the feasibility.

Was pretty envious of TipTap (a ProseMirror wrapper) a few years ago when it was a Vue exclusive, looks like it's in React now so could be a good bet?

For an MVP I would say just pick an editor that covers the features you want and has a data format that can be easily converted to something else if/when needed. Haven't actually tried to do it, but Quill's flat data model does not seem very easy to transfer outside of having it render as HTML and render back into whatever format you want.

**Comment by brooksdra** [comment] 2022-07-14 13:31
What I'd like to do is extend the code </> feature to change the background color, maybe the default font, and add a unique name for each unique code segment. I'd like to be able to find the individual code segments in the document to make a dynamic lookup table.

**Comment by brooksdra** [comment] 2022-07-14 13:44
I'm considering cloning the repo to develop this feature myself, but have no idea where to start with this kind of project.

**Comment by padraigfl** [comment] 2022-07-14 13:51
Do you mean each segment as in a block of code between other pieces of rich text? That _should_ be doable by expanding the code module (they were called "blots" iirc) for code and giving it an ID attribute that gets added to the wrapper element or something? 

In general Quill's pains mostly occur when dealing with nested content (single level lists barely work, tables are a nightmare)

**Comment by brooksdra** [comment] 2022-07-17 20:18
Yes, I want precisely the same block command as code with a few new features. I was just reviewing the code this weekend, and think you are exactly right about the code. The code block Thanks

**Comment by benbro** [comment] 2024-01-30 18:52
[v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2) just released.

**Closed by benbro** 2024-01-30 18:52 UTC
