### ISSUE TITLE
All rich text formatting plus the font color gets removed on double Enter

### ISSUE THREAD

**Issue by aliarshad9691** [quilljs/quill#386] opened 2015-05-30 07:56 UTC
Repro Steps:

1) Apply formatting (e.g color, bold)
2) start typing
3) Press enter twice

All formatting would be lost...

**Comment by jocoolie** [comment] 2015-06-01 16:42
Clarification: 
A) Choose the formatting desired before typing. 
B) Type some text. 
C) Hit enter and type some more: the formatting continues.
D) Hit enter twice: the formatting of text on this line is the default.

A single newline `<br />` character retains the formatting, but moving to a new container `<div>` terminates the formatting, and it will not be applied to any further text without selecting and reapplying the style.

I think the issue is that the new `<div>` is created with no style attributes.

I think that this behavior is intuitive for things like "headings", with bold or large text, but not so much if writing several paragraphs in dark blue or a specific font (like code or quotations).

**Comment by jcludwig** [comment] 2015-06-15 01:48
This also appears to happen if you type some text and then backspace until the beginning of the line. The formatting is reset.

**Comment by peterweck** [comment] 2015-06-25 00:19
I'm having issue with the formatting changes after a single Enter (new line). Steps to reproduce:

1) Set font to Monospace, font-size to large
2) Type some text and hit Enter
3) New line is back to Normal size

Also if you start a line with one Font and change it another font to on the same line, the new font changes after you hit Enter.

The is greatly impacting the usability of the editor.

**Comment by willrowe** [comment] 2015-06-25 08:36
There's a bug that's preventing all of the formats from being re-applied. I'm about to submit a PR to fix it.

**Comment by willrowe** [comment] 2015-06-25 20:55
To clarify, this will only fix the issue mentioned by @peterweck and not the original issue.

**Comment by benbro** [comment] 2015-07-28 01:14
As the PR says, formatting are still lost on double Enter.
Maybe this issue should be reopened?

**Comment by jcludwig** [comment] 2015-08-04 03:34
The original bug still repros on the front page. Can we get this re-opened? @peterweck's issue should probably have been a separate bug...

**Comment by willrowe** [comment] 2015-08-04 03:36
I agree that this should be re-opened. In order to fix this bug though, some major changes will need to be made to how formats are handled.

**Comment by aliarshad9691** [comment] 2015-08-04 06:03
Yes this issue still persists... can we reopen it?

**Comment by jhchen** [comment] 2016-05-04 07:41
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release

**Closed by jhchen** 2016-05-04 07:41 UTC
Labels: bug, fixed-in-1.0
