### ISSUE TITLE
GET-Request on pasting images even if they are disabled

### ISSUE THREAD

**Issue by Der-Zauberer** [quilljs/quill#3801] opened 2023-06-14 11:58 UTC
I tried to disable images in the editor. I managed that successfully, so the image can no longer be pasted in the editor but it does trigger a GET-Request for the image anyway.

I used the issue https://github.com/quilljs/quill/issues/1108 to disable the image and followd exactly the steps form the first answer.

**Steps for Reproduction**

1. Copy a image in the clipboard
2. Paste in in the editor with images disabled

**Expected behavior**: No request is triggerd

**Actual behavior**: A get GET-Request to the image was triggert

![grafik](https://github.com/quilljs/quill/assets/35459249/8d2dc55b-0a65-42dc-90e3-3852680a4d26)

**Platforms**:

![grafik](https://github.com/quilljs/quill/assets/35459249/adde8781-646f-470a-8dde-a196c4935daa)

**Version**: 22.0.0

Run 22.0.0` to find out

**Comment by coastalberry** [comment] 2023-06-23 18:51
I can confirm this behavior on version 1.3.6 as well. 

Here's a _incomplete_ solution that works for me. I say incomplete because it **only allows for plain text pastes and prevents all further processing** (and thereby prevents the `GET` requests for images):

```javascript
// Define the custom Clipboard module
const Clipboard = Quill.import('modules/clipboard');

class PlainTextClipboard extends Clipboard {
  // Override the onPaste method
  onPaste(e) {
    e.preventDefault();
    
    // Get the plain text from the clipboard
    const clipboardData = e.clipboardData || window.clipboardData;
    const plainText = clipboardData.getData('text/plain');
    
    // Insert the plain text into the editor
    const index = this.quill.getSelection().index;
    this.quill.insertText(index, plainText, Quill.sources.USER);
  }
}

// Register the custom module with Quill
Quill.register('modules/clipboard', PlainTextClipboard);
```

Please note that I have not thoroughly tested this beyond resolving the `GET` issue.

**Closed** 2024-04-17 11:20 UTC
