### ISSUE TITLE
[Next js] How To Dynamic Import quill for next app router

### ISSUE THREAD

**Issue by rahulsya** [quilljs/quill#4129] opened 2024-04-19 15:30 UTC
I facing an issue when trying to import quill as a dynamic import for next app router. 
I need an example of how to dynamic import quill on next app router

My code is like this 
![image](https://github.com/quilljs/quill/assets/48597821/24bbaf2c-a4aa-4005-b860-769ca16787fe)

why do I need to import as dynamic because I meet the error `ReferenceError: document is not defined`
![image](https://github.com/quilljs/quill/assets/48597821/bc409b88-b762-4c2b-97ce-85cbc628ef50)

Thank you..

**Comment by shareefalis** [comment] 2024-04-19 23:32
You need to run the Quill code in a client rendering enviroment for Next.js.
https://nextjs.org/docs/app/building-your-application/rendering#rendering-environments

**Comment by luin** [comment] 2024-04-20 07:09
Closing as there are answers. Quill only runs on client side.

**Closed by luin** 2024-04-20 07:09 UTC
Labels: question

**Comment by Quietly-20201113** [comment] 2024-04-28 03:08
```tsx
"use client"

import { memo, useEffect, useRef } from "react";
import Quill from "quill";
import "quill/dist/quill.snow.css"

/**
 * Next 13.5.6
 * quill 2.0.0
 * 
 */
const QuillRenderPage = memo(() => {

    const quill = useRef<Quill | null>(null)
    const toolbarOptions = [
        ["bold", "italic", "underline", "strike"], // 加粗，斜体，下划线，删除线
        ["blockquote", "code-block"], // 引用，代码块
        [{ header: 1 }, { header: 2 }], // 标题，键值对的形式；1、2表示字体大小
        [{ list: "ordered" }, { list: "bullet" }], // 列表
        [{ script: "sub" }, { script: "super" }], // 上下标
        [{ indent: "-1" }, { indent: "+1" }], // 缩进
        [{ direction: "rtl" }], // 文本方向
        [{ size: ["small", false, "large", "huge"] }], // 字体大小
        [{ header: [1, 2, 3, 4, 5, 6, false] }], // 几级标题
        [{ color: [] }, { background: [] }], // 字体颜色，字体背景颜色
        [{ font: [] }], // 字体
        [{ align: [] }], // 对齐方式
        ["clean"], // 清除字体样式
        ["image", "video"], // 上传图片、上传视频               // remove formatting button
      ];
     
      //富文本配置
      const options = {
        modules: {
          toolbar: toolbarOptions,
          history: {
            delay: 2000, // 2s记录一次操作历史
            maxStack: 200, // 最大记录200次操作历史
         },
        },
      
        placeholder: "请输入...",
        theme: "snow",
      };

        useEffect(() => {
            quill.current = null;
            quill.current = new Quill("#editor", options);
        }, [])



    return (
        <div className="flex w-full h-full">
           <div className="flex-1">
                <div id="editor"></div>
           </div>
           <div className="flex-1">
                预览
           </div>
        </div>
    )
})

QuillRenderPage.displayName = "QuillRenderPage"


export default QuillRenderPage
```

依然报错 
```js
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/work/sample_code/github/next-redux-pages/node_modules/.pnpm/quill@2.0.0/node_modules/quill/core/emitter.js (7:3)
```

**Comment by luin** [comment] 2024-04-28 03:48
@Quietly-20201113 The cause should be pretty similar: QuillRenderPage can only be rendered on the client side as it requires `document` to be present.

**Comment by Quietly-20201113** [comment] 2024-04-28 06:01
> @Quietly-20201113原因应该非常相似：QuillRenderPage 只能在客户端呈现，因为它需要`document`存在。

哦哦,得提出去引用,解决方案
```tsx
const QuillRenderPage = dynamic(() => import("@/components/ClientRender/QuillRender"), {
    ssr: false,
    loading: () => <div>初始化编辑器...</div>,
})
```
