### ISSUE TITLE
[Parchment] Maximum optimize iterations when creating Table blots

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2455] opened 2019-01-08 11:31 UTC
I am trying to understand how blots work and I wanted to recreate step by step the Table example from the parchment repo. For now I wrote the following code:

```javascript
import Quill from 'quill';
import { ContainerBlot } from 'parchment';

class TableBody extends ContainerBlot {}
TableBody.blotName = 'table-body';
TableBody.tagName = 'TBODY';

class Table extends ContainerBlot {}
Table.tagName = 'TABLE';
Table.blotName = 'table-container';
Table.allowedChildren = [TableBody];

Quill.register(Table, true);
```

and the main node on which Quill is instantiated has the following content:

```html
<table>
    <tbody>
        <tr>
            <th><b>Title</b></th>
        </tr>
        <tr>
            <td >
                  Some row
            </td>
        </tr>
    </tbody>
</table>
```

and I get the following error:
> bundle.js:231739 Uncaught Error: [Parchment] Maximum optimize iterations reached

**Steps for Reproduction**

-

**Expected behavior**:

I would expect only the `<table><tbody></tbody></table>` to render.

**Actual behavior**:

Error

**Platforms**:

Chrome MacOS Mojave

**Version**:

2.0.0-dev

**Comment by Kiaba** [comment] 2021-04-21 14:45
I have the same problem.

**Comment by salkao** [comment] 2021-09-22 20:33
Any updates on this one? I also have the same issue after extending Header class.

**Comment by MonkeyInWind** [comment] 2021-09-29 10:04
+1

**Comment by inventivejon** [comment] 2021-11-14 14:27
+1

**Comment by Grewer** [comment] 2022-03-07 08:32
My guess is that his blotName is a duplicate of one of the existing ones

**Comment by twada7777** [comment] 2022-03-11 00:40
Dose the following work?

- class Table extends ContainerBlot {}
+ class Table extends ContainerBlot {
+   optimize(context);
+   if (this.domNode.tagName !== this.statics.tagName[0]) {
+     this.replaceWith(this.statics.blotName);
+   }
+ }

- Table.tagName = 'TABLE';
+ Table.tagName = ['TABLE'. 'T'];

see also https://github.com/quilljs/quill/blob/develop/formats/bold.js

**Comment by nehalsoni23** [comment] 2023-11-02 10:45
Is there any update on this issue?

**Closed** 2024-04-17 11:19 UTC
