### ISSUE TITLE
entering a newline with bold or italics results in a <span class="ql-cursor></span> with a unicode character inside the span, potentially causing character encoding problems with databases

### ISSUE THREAD

**Issue by aaron-hanson** [quilljs/quill#1682] opened 2017-09-01 19:52 UTC
If you go into an editor and end with a newline while bold or italics is on, the value ends up having a "<span class="ql-cursor></span>" at the end, but the span is actually not empty.  This can be seen by trying to regex replace this span with something like:

elementValue = elementValue.replace(/<span class="ql-cursor"><\/span>/g, "");

...which does not work.  Instead, a regex like this is needed in order to replace the span, indicating that there is some content inside it:

elementValue = elementValue.replace(/<span class="ql-cursor">**[^<]***<\/span>/g, "");

**Steps for Reproduction**

1. Visit quilljs.com
2. Clear out all data from the editor
3. Turn on bold
4. Enter in some text and hit enter for a newline
5. Inspect the content with Chrome developer tools or similar
6. Notice that the newline's paragraph's content is something like: `<p><strong><span class="ql-cursor">&#65279;</span></strong></p>`

**Expected behavior**:
The editor's content should be saveable to a database like MySQL, into a non-unicode column, as we have not entered any unicode characters.

**Actual behavior**:
Server or database errors like: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xEF\xBB\xBF</s...' for column 'text' at row 1"

**Platforms**:
Chrome

**Version**:
Quill 1.3.1

**Comment by benbro** [comment] 2017-09-01 20:20
Quill work with Delta format.
The API let you get the contents of the editor with [editor.getContents()](https://quilljs.com/docs/api/#getcontents).

There is a discussion for how to get the raw HTML from the editor but it's not part of the API and isn't  safe to send to the server.
https://github.com/quilljs/quill/issues/903#issuecomment-243844178

**Comment by aaron-hanson** [comment] 2017-09-01 20:32
@benbro yes, I've seen that, but we are not interested in persisting the Delta, and then have to parse that with an editor just in order to display the rich text.  Far easier for us is persisting the rich text itself, which works fine, except for this one unicode character.  For now, we workaround by stripping out this span with the unicode character.

**Comment by benbro** [comment] 2017-09-01 20:37
If you place your cursor in this [example](https://codepen.io/anon/pen/eExKmz) and wait 5 seconds, the innerHTML in the console won't have the cursor span.

Again, you shouldn't trust raw HTML from the end user. Please use getContents() in the API.
There is not bug here.
Closing.

**Closed by benbro** 2017-09-01 20:37 UTC

**Comment by aaron-hanson** [comment] 2017-09-01 20:40
@benbro - that's all fine and well, but we sanitize everything from the user anyhow.  Now we just sanitize the offending Quill span as well...easy enough.  It's just odd that this span should be output by Quill in the first place.

**Comment by benbro** [comment] 2017-09-01 20:41
Quill doesn't output this span as demonstrated in the CodePen above. Did you check it?

**Comment by aaron-hanson** [comment] 2017-09-01 20:44
Yes, I see your example works, but only if I wait 5 seconds.

**Comment by benbro** [comment] 2017-09-01 20:46
The timeout just give you enough time to place your cursor to show that it isn't included in the HTML.
If you have further questions please use [StackOverflow](https://stackoverflow.com/search?q=quill).

**Comment by aaron-hanson** [comment] 2017-09-01 20:50
The problem is that your example isn't the state I was describing.  Try clearing the editor, entering bold text on one line, hitting enter for a newline, and then inspecting the html.  The span is there in that case, same as I'm seeing in our app's usage of Quill.

**Comment by aaron-hanson** [comment] 2017-09-01 21:19
@benbro - for instance, try this [codepen example](https://codepen.io/anon/pen/rzPKwm?editors=1111) based on the one you sent me.  Put your cursor at the end of the "test" text, and hit enter.  You'll see the console log the <span class="ql-cursor"></span>, which also contains the unicode character inside the span.

**Comment by jhchen** [comment] 2017-09-01 21:22
The reason the `ql-cursor` is there is to control the formatting of the next character you type. Browsers do not consistently allow selection around empty text so there has to be a real character so we chose a zero width space character. As already said this is not a bug and we recommend using `getContent` and `Deltas` but if you want to sanitize raw HTML it's your application and codebase.

**Comment by alexkrolick** [comment] 2017-11-17 08:29
This seems to cause some _weird_ interactions with React, but only on Android. See https://github.com/zenoamaro/react-quill/issues/282.
