### ISSUE TITLE
Multiple Instances of Quill for Complex Layouts

### ISSUE THREAD

**Issue by philmaker1** [quilljs/quill#1506] opened 2017-06-13 02:14 UTC
I'm interested in creating complex layouts using Quill. This means that I would also like to have multiple Quill instances share a toolbar. I would also like to a new Quill format which will present a column of Quill instances. Has anyone done any of this yet using Quill or should I build it myself?

**Comment by jhchen** [comment] 2017-07-16 22:20
Looks like a duplicate of #633

**Closed by jhchen** 2017-07-16 22:20 UTC
