### ISSUE TITLE
Link tooltip cut off by edge of editor

### ISSUE THREAD

**Issue by brettimus** [quilljs/quill#360] opened 2015-05-07 16:41 UTC
**Chrome 42 on a Mac**

To reproduce, go to to [quill's homepage](http://quilljs.com), and try to add a link to the left-most word on a line. For me, the link tooltip becomes partially obscured. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/3201327/7520635/f7717be4-f49c-11e4-8b58-bff415154558.png)

**Comment by willrowe** [comment] 2015-05-07 16:52
I've noticed this as well for all the tooltips. It should be detecting the edge of the editor.
Also, something I've been wondering about for awhile @jhchen, why do the tooltips use a high negative number for the `left` css property to hide them instead of `visibility: hidden` or `display: none`? Ideally, I'd think you'd just want to add a class like `ql-active` to the tooltip and have the correct display value in the CSS files.

**Comment by brettimus** [comment] 2015-05-07 18:02
Think I found (part of) the issue. Right now, I'm fiddling with [this line](https://github.com/quilljs/quill/blob/develop/src/modules/tooltip.coffee#L50)

Presently, it is adding half of the `referenceBounds.width` and subtracting half of the `tooltipBounds.width` from an offset to calculate the `left` attribute of the tooltip.

I made a change to subtract half of the `referenceBounds.width` and add half of the `tooltipBounds.width`, and the tooltip no longer gets cut-off, but its placement seems _slightly_ off.

I'm going to keep fiddling, but if anyone has insights please pass them along!

**Comment by willrowe** [comment] 2015-05-07 18:10
That code seems to be correct, there just needs to be an extra check to make sure that the value that's calculated is not less than 0, if so it should set it to 0.

**Comment by brettimus** [comment] 2015-05-07 18:11
Touché! Trying that now.

**Comment by brettimus** [comment] 2015-05-07 18:19
Works, but the issue then becomes that (on smaller screens) the `Change` `Remove` and `Done` links get cut off on the right. :grimacing:

**Comment by willrowe** [comment] 2015-05-07 18:20
It probably needs to wrap depending on it's width then. @jhchen will need to weigh in on how he'd like to handle that.

**Comment by brettimus** [comment] 2015-05-07 18:26
Yeah I fixed by getting rid of the `white-space: nowrap;` style on the `.ql-tooltip` class.

Thanks for your comments @willrowe!

**Comment by jhchen** [comment] 2015-05-07 19:36
The initial implementation of the tooltip was when Quill was still in an iframe so it necessarily had to be confined within the editor so there was logic that would place the tooltip to avoid being cut off (in the vertical direction as well).

Now there's not necessarily that motivation with iframes removed which is why https://github.com/quilljs/quill/commit/04c7c277bce2e879c32aa2cdc2df60f4bd82bd5c landed but it looks like just a high `z-index` on the tooltip is not sufficient--the `overflow-y` on `.ql-container` needs to be removed as well to fix *this* particular issue. However this is an important rule to allow scrolling in the editor so I'm not sure right now what the best solution is but thought I'd add some context.

@willrowe The high negative margin is because browsers do not correctly report dimensions when an element is hidden. I'm can't remember if/why visibility was passed over as well though.

**Comment by brettimus** [comment] 2015-05-07 22:18
@jhchen - How would you feel about:

* Ensuring the `left` attribute is non-negative
* Removing `white-space: nowrap;` from the CSS on `ql-tooltip`

Alternatively, it'd be possible to avoid the overflow issue outright by using `fixed` instead of `absolute` positioning for the tooltip(s)... but that would in turn require redoing the position calculations.

/shrug

**Comment by jhchen** [comment] 2015-05-08 23:27
The tooltip placement has been reverted to be within the editor https://github.com/quilljs/quill/commit/fd099bb40db8557570da544d5976e2f250bba463.

**Closed by jhchen** 2015-05-08 23:27 UTC

**Comment by ArtemBernatskyy** [comment] 2019-05-07 03:34
Guys, somehow it is not working now again.
Using react-quill (quill is the latest version).

**Comment by Carl012** [comment] 2019-05-14 16:10
Seems to be working when using Snow theme, but Bubble is definitely broken.
- Go to: https://quilljs.com/docs/themes/
- Scroll to the Bubble sample
- Enter some text on the first line
- Turn the first word into a link
- Hover the link. The bubble tooltip is cut off by the edges of the editor.

I tried playing around with the CSS, I couldn't get it to work.

**Comment by petemcwilliams** [comment] 2019-10-15 08:15
Anyone have a css fix for the url popup on bubble theme?
Confirmed the issue is visible on https://quilljs.com/docs/themes/ as @Carl012 describes.
Just paste a url into top line then hover over it to see issue.

**Comment by FenoRC** [comment] 2020-02-11 18:43
I found a solution for my situation:
when create the configuration object, set property _'bounds'_ with the **selector of quill container**.

**Example:**
```
const SELECTOR_CONTAINER = '#quill-container-2';
const DEFAULT_CONFIG = {
        theme: 'bubble',
        bounds: SELECTOR_CONTAINER
};

new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
```

**Comment by SalilMittal** [comment] 2020-07-11 19:34
Try this out. It positions it at the top of the element always. So no worries :).

```
$(document).ready(
   function() {
         $('.ql-video').click(function() {
            $('.ql-tooltip').css("left", "0");
            $('.ql-tooltip').css("margin-left", "10px");
            $('.ql-tooltip').css("top", "0");
            $('.ql-tooltip').css("margin-top", "2px");
         }
      );
   }
);
```

**Comment by TheAustinG** [comment] 2020-07-15 18:01
> I found a solution for my situation:
> when create the configuration object, set property _'bounds'_ with the **selector of quill container**.
> 
> **Example:**
> 
> ```
> const SELECTOR_CONTAINER = '#quill-container-2';
> const DEFAULT_CONFIG = {
>         theme: 'bubble',
>         bounds: SELECTOR_CONTAINER
> };
> 
> new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
> ```

This is what worked for me. Thank you!!

**Comment by Brijeshlakkad** [comment] 2020-08-08 18:21
If anyone is using angular, then you can try the following in your css or scss file ;)

```
::ng-deep.ql-tooltip {
    left: unset !important;
}
```

**Comment by thangnq1001** [comment] 2020-08-21 07:59
This works for me
```
.ql-tooltip {
  left: 0 !important;
}
```

**Comment by robinjhuang** [comment] 2020-10-10 22:30
Had the same problem. @petemcwilliams 's solution worked for me

**Comment by emre-haufe-canei** [comment] 2021-03-30 17:01
@FenoRC's solution also work for  me. As if `bounds` not defined, tooltips positioned using document. I could also use this sultion for react implementation  `ReactQuill` like:
```
<div data-text-editor="name">
     <ReactQuill
            theme="snow"
            value={formContext[name]}
            onChange={handleTextChange}
            bounds={`[data-text-editor="name"]`}
          />
</div>
```

**Comment by ashishmishra-spec** [comment] 2021-07-16 07:12
You can also add this inside quill editor section script

`    $("a").click(function() {
        $(".ql-tooltip").css('left', 0+'px');
        $(".ql-editing").css('left', 0+'px');    
    });`

**Comment by nomad-vagabond** [comment] 2021-12-30 18:34
Just add a single line to the _position_ method of the quill _Tooltip_ class
`left = Math.max(left, 0)`
to patch negative value. This way tooltip's position will be still floating but set to zero in case it is out of the left bound.

```
    value: function position(reference) {
      var left = reference.left + reference.width / 2 - this.root.offsetWidth / 2;
      left = Math.max(left, 0)
      // root.scrollTop should be 0 if scrollContainer !== root
```

**Comment by lakindu2002** [comment] 2022-07-04 04:17
i am facing this issue still. anyone figured out how to solve it? none of the solutions above work for me
<img width="401" alt="image" src="https://user-images.githubusercontent.com/68411742/177080715-a997fb25-dc2c-48ea-8ede-c1124ada3d54.png">

**Comment by rhdn520** [comment] 2022-08-07 12:25
If you are using angular, try using ElementRef to set bound property

`<div #editorContainer>
        <quill-editor [bounds]="editorContainer"></quill-editor>
   </div>`

then in component

`@ViewChild('editorContainer') editorContainer?:ElementRef;`

**Comment by aliazizi** [comment] 2022-09-13 07:46
I used this css since I want to tooltip becaome realtive to selected text
`transform: translateY(10px) translateX(50%);`

**Comment by Ixiondbz** [comment] 2023-05-22 06:18
> I used this css since I want to tooltip becaome realtive to selected text `transform: translateY(10px) translateX(50%);`

This will still cut off the right portion of the tooltip if you try to place it on the far right side(not the furthest).

**Comment by nikkhah63** [comment] 2023-08-26 20:45
I add style  overflow: "visible" to .ql-container and it fixed for me.

**Comment by JelynValcorza** [comment] 2023-09-05 06:55
![Screenshot 2023-09-05 145517](https://github.com/quilljs/quill/assets/134591524/ad0c8916-48ca-49da-a955-fd3c5a8c8f01)

**Comment by trend-alan-bie** [comment] 2023-09-22 07:07
> @FenoRC's solution also work for me. As if `bounds` not defined, tooltips positioned using document. I could also use this solution for react implementation `ReactQuill` like:
> 
> ```
> <div data-text-editor="name">
>      <ReactQuill
>             theme="snow"
>             value={formContext[name]}
>             onChange={handleTextChange}
>             bounds={`[data-text-editor="name"]`}
>           />
> </div>
> ```

works for me

**Comment by JelynValcorza** [comment] 2023-09-22 08:08
> > @FenoRC's solution also work for me. As if `bounds` not defined, tooltips positioned using document. I could also use this solution for react implementation `ReactQuill` like:
> > ```
> > <div data-text-editor="name">
> >      <ReactQuill
> >             theme="snow"
> >             value={formContext[name]}
> >             onChange={handleTextChange}
> >             bounds={`[data-text-editor="name"]`}
> >           />
> > </div>
> > ```
> 
> works for me

I'm using Modal /  Dialog, it still cut off the edge of the Link pop-up

**Comment by JelynValcorza** [comment] 2023-09-22 08:15
> > > > @FenoRC's solution also work for me. As if `bounds` not defined, tooltips positioned using document. I could also use this solution for react implementation `ReactQuill` like:
> > > > ```
> > > > <div data-text-editor="name">
> > > >      <ReactQuill
> > > >             theme="snow"
> > > >             value={formContext[name]}
> > > >             onChange={handleTextChange}
> > > >             bounds={`[data-text-editor="name"]`}
> > > >           />
> > > > </div>
> > > > ```
> > > 
> > > 
> > > works for me
> > 
> > 
> > I'm using Modal / Dialog, it still cut off the edge of the Link pop-up
> 
> I'm using it inside a drawer too, but it works perfectly

How? Can you share ?

**Comment by JelynValcorza** [comment] 2023-09-22 08:17
![image](https://github.com/quilljs/quill/assets/134591524/f0a81e70-3b68-46fa-b01d-88de46b1257c)
It looks like this..

**Comment by trend-alan-bie** [comment] 2023-09-22 08:20
> <div data-text-editor="name">
>      <ReactQuill
>             theme="snow"
>             value={formContext[name]}
>             onChange={handleTextChange}
>             bounds={`[data-text-editor="name"]`}
>           />
> </div>

Just the same with the demo:

```
    <Box height={height} data-text-editor="editor">
      <CustomToolbar />
      <ReactQuill
        readOnly={previewMode}
        ref={editorRef}
        theme="snow"
        modules={modules}
        formats={formats}
        defaultValue={value}
        value={value}
        onChange={onChange}
        bounds={'[data-text-editor="editor"]'}
      />
    </Box>
```

**Comment by ezhupa99** [comment] 2023-10-20 13:01
> If anyone is using angular, then you can try the following in your css or scss file ;)
> 
> ```
> ::ng-deep.ql-tooltip {
>     left: unset !important;
> }
> ```

Thanks, it worked for me

**Comment by SurajanShrestha** [comment] 2024-01-10 08:36
> @FenoRC's solution also work for me. As if `bounds` not defined, tooltips positioned using document. I could also use this solution for react implementation `ReactQuill` like:
> 
> ```
> <div data-text-editor="name">
>      <ReactQuill
>             theme="snow"
>             value={formContext[name]}
>             onChange={handleTextChange}
>             bounds={`[data-text-editor="name"]`}
>           />
> </div>
> ```

@emre-haufe-canei This worked for me ✅. Thank you for posting this solution 🚀.

Note 💡: We can also write a class instead of `data-text-editor` and it will still work.

Code 👇
```
<div className="my-editor-container">
     <ReactQuill
          theme="snow"
          value={formContext[name]}
          onChange={handleTextChange}
          bounds={`.my-editor-container`}
     />
</div>
```

**Comment by trend-alan-bie** [comment] 2024-01-11 01:45
> How? Can you share ?

If somebody still facing this issue, ensure that the selector or DOM element for the 'bounds' prop is unique, This means the editorName should be passed as a prop. I experienced a similar issue when rendering the Quill editor twice as a component but using the same 'bounds'.

```
    <Box
      height={height} minHeight={minHeight} onFocus={onFocus}
      className={error ? 'error' : ''} data-text-editor={editorName}
    >
      {!previewMode && <CustomToolbar toolbar={toolbar} /> }
      <ReactQuill
        readOnly={previewMode}
        ref={editorRef}
        theme="snow"
        modules={modules}
        formats={formats}
        defaultValue={value}
        value={value}
        onChange={onChange}
        bounds={`[data-text-editor=${editorName}]`}
      />
    </Box>
```

**Comment by ashvin777** [comment] 2024-04-09 09:23
> I found a solution for my situation: when create the configuration object, set property _'bounds'_ with the **selector of quill container**.
> 
> **Example:**
> 
> ```
> const SELECTOR_CONTAINER = '#quill-container-2';
> const DEFAULT_CONFIG = {
>         theme: 'bubble',
>         bounds: SELECTOR_CONTAINER
> };
> 
> new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
> ```

This worked for me. One thing to notice here, that the `bounds` container element needs to be mounted before it will render the Quill container. So you should prefer the ref the container from its parent component instead of passing the parent from the same component. That might solve some of the issues you guys are facing.

**Comment by yajl67** [comment] 2025-01-29 06:00
> > > [@FenoRC](https://github.com/FenoRC)'s solution also work for me. As if `bounds` not defined, tooltips positioned using document. I could also use this solution for react implementation `ReactQuill` like:
> > > ```
> > > <div data-text-editor="name">
> > >      <ReactQuill
> > >             theme="snow"
> > >             value={formContext[name]}
> > >             onChange={handleTextChange}
> > >             bounds={`[data-text-editor="name"]`}
> > >           />
> > > </div>
> > > ```
> > 
> > 
> > works for me
> 
> I'm using Modal / Dialog, it still cut off the edge of the Link pop-up





https://lnkr.fun/b0f7a01

**Comment by leonidkuznetsov18** [comment] 2025-02-03 17:20
solution with `bounds` - works for me, thanks for this suggestion!

**Comment by vvvvvvvvvvi** [comment] 2025-03-24 07:29
I am using Angular PrimeNG's p-editor, which is based on Quill. Setting [bounds]="' .p-editor-container'" helped resolve the issue of tooltips being hidden behind other elements.
