### ISSUE TITLE
Cursor jumps, when making marked text bold or italic

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#2603] opened 2019-05-07 11:34 UTC
I use quill with polymer 2.0 but, the toolbar buttons show unexpected behaviour. I made a gif showing the problem.

![Quill](https://user-images.githubusercontent.com/34607816/57296016-2fda8480-70cc-11e9-9321-effe24e3ebee.gif)
```
<div id="toolbar" class="full-width">
				<select class="ql-size">
					<option value="small"></option>
					<option selected></option>
					<option value="large"></option>
					<option value="huge"></option>
				</select>
				<span class="ql-formats">
    			  <button class="ql-bold"></button>
    			  <button class="ql-italic"></button>
    			  <button class="ql-underline"></button>
    			  <button class="ql-strike"></button>
    			</span>
			</div>
			<div id="editor" class="full-width">
			</div>

		<style include="shared-styles">
		</style>
	</template>


	<script>
        class InfotextsEditor extends UtilsMixin(Polymer.Element) {
            static get is() {
                return 'infotexts-editor'
            }

            connectedCallback(){
                super.connectedCallback();
                var editor = Polymer.dom(this.root).querySelector('#editor');
                var toolbar = Polymer.dom(this.root).querySelector('#toolbar');
                var options = {
                    modules: {
                        toolbar: toolbar
                    },
					placeholder: '...',
                    theme: 'snow'
                };
                var quill = new Quill(editor, options);
                quill.focus();
            }
        }

        customElements.define(InfotextsEditor.is, InfotextsEditor);
	</script>
```

**Expected behavior**: I expect the selected text to become bold/italic etc.

**Actual behavior**: The cursor is moved to the begin and there the e

**Platforms**:

Version: 1.3.6, Browser: Chrome
Also: Edge and Firefox show similar behaviour(i.e. Edge: Cursor jumps to end)
OS: Win10 1809

**Comment by Shreyas-BS** [comment] 2021-11-22 12:10
I am also facing the same issue with Lit Element. Any fix for this issue?

**Comment by canta91** [comment] 2022-04-28 08:42
Same issue, anyone had fixed?

**Comment by ammarlokh95** [comment] 2023-08-15 19:16
I'm running into a similar issue with quill on angular using quill-ngx. Is this still unresolved?

**Comment by ammarlokh95** [comment] 2023-08-15 20:57
For context, I am trying to use Quill in component that is encapsulated in a Shodow Dom. It works as expected outside of the shadow dom. My guess is that the Quilljs code is trying to access some elements on the document but is unable to because it is inaccessible from the dom

**Closed** 2024-04-17 11:19 UTC

**Comment by TechQuery** [comment] 2024-04-25 13:22
Quill 2.0.0 has same bugs with Web components: https://github.com/EasyWebApp/quill-cell/pull/1/commits/8bf3c6d8da477c71f6cbb5be1140460141b30f33

## Reproduce

1. open the test page code in Cloud IDE: https://gitpod.io/?autostart=true#https://github.com/EasyWebApp/quill-cell/pull/1/commits/8bf3c6d8da477c71f6cbb5be1140460141b30f33

2. run `pnpm i  &&  npm start` to open the test page
