### ISSUE TITLE
Typing in a specific sequence of keys causes inability to type into editor in Firefox

### ISSUE THREAD

**Issue by jasokant** [quilljs/quill#1272] opened 2017-01-16 20:09 UTC
**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/ygadPe in Firefox
2. Click into Quill Editor
3. Press Enter
4. Press Delete
5. Try to enter more characters

**Expected behavior**:
Inputted characters show up in editor

**Actual behavior**:
No change. Work around this by clicking into editor again and typing.

**Platforms**:

Firefox 50.1.0
OSX 10.11.5 

**Version**:

1.1.6

**Comment by dons20** [comment] 2017-01-18 10:39
I went ahead and created a GIF of the bug. Note that after I deleted the text from the editor, I was trying to type repeatedly, but it would only resume typing when I clicked the editor.

![quillbuggedfirefox](https://cloud.githubusercontent.com/assets/3958349/22060831/6d030b9c-dd40-11e6-9d5b-abd26c8b8e58.gif)

[Quill bug on Firefox](https://gfycat.com/CarefreeBriefArthropods)

**Comment by jhchen** [comment] 2017-01-21 09:33
I think this is a duplicate of #1254. Upgrading the codepen to 1.2.0 fixes the issue.

**Closed by jhchen** 2017-01-21 09:33 UTC
