### ISSUE TITLE
2.0.0-dev.4 is not working with angular version 13 and above

### ISSUE THREAD

**Issue by agholipour** [quilljs/quill#3524] opened 2022-01-23 22:37 UTC
on execution I am receiving the following error on v 13 , (works with 12)
Uncaught SyntaxError: Unexpected token ':'
    at Object../node_modules/quill-delta/dist/Op.js (:4200/vendor.js:61536:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./node_modules/quill-delta/dist/Delta.js?:9:28)
    at Object../node_modules/quill-delta/dist/Delta.js (:4200/vendor.js:61504:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./core/quill.js?:6:69)
    at Module../core/quill.js (:4200/vendor.js:59876:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./core.js?:2:69)
    at Module../core.js (:4200/vendor.js:59780:9)

package.json

"dependencies": {
    "@angular/animations": "^13.0.2",
    "@angular/cdk": "^13.0.2",
    "@angular/cli": "^13.0.3",
    "@angular/common": "^13.0.2",
    "@angular/compiler": "^13.0.2",
    "@angular/compiler-cli": "^13.0.2",
    "@angular/core": "^13.0.2",
    "@angular/forms": "^13.0.2",
     "quill": "^2.0.0-dev.4",
     "quill-better-table": "^1.2.10",
     "ngx-quill": "^16.1.1",
     ...}

running on google chrome

Could you please help me to fix this. Thanks

**Comment by robrez** [comment] 2022-01-27 21:19
Duplicate: https://github.com/quilljs/quill/issues/3497

**Comment by Un1xMida** [comment] 2022-10-30 07:22
any updates on this ? @robrez

**Comment by robrez** [comment] 2022-11-03 15:16
@Un1xMida I'm not affiliated w/ this project .. am trying to recall what led me here exactly.  My solution to this problem might not be pragmatic for most.. but I used `rollup` to re-bundle quilljs as ESM and I changed my code to import that vendor bundle

**Comment by Huseyin-altun** [comment] 2023-08-22 12:13
@robrez Can you please share a demo of stackblitz

**Comment by benbro** [comment] 2024-01-29 18:35
Duplicate of https://github.com/quilljs/quill/issues/3497 and fixed in [v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)

**Closed by benbro** 2024-01-29 18:35 UTC
