### ISSUE TITLE
Toolbar not working with Android autocompleter

### ISSUE THREAD

**Issue by visore** [quilljs/quill#444] opened 2015-08-09 15:40 UTC
I have problems with the formatting tools when using Quill on Android (Firefox, Chrome and the Android browser). When you select a formatting control (eg: font, size, bold, etc) and type, the control is automatically deselected. Sometimes the control stays selected, but the text is not formatted accordingly. Other times only one of the formats are used, that is, if you select bold, italics and underline, only one of the formats are applied (mostly the one selected first). 

Is this just me or did someone else notice this problem? I've tested it with the default editor on Quill's homepage using Android 5 with the latest version of Firefox, Chrome and the default Android browser.

**Comment by jhchen** [comment] 2015-08-10 22:26
I was able to reproduce formatting issues on Firefox on an Android tablet. I'm not seeing anything wrong on the Android browser or Chrome on the quilljs.com homepage. Can you provide detailed reproductions steps for Android Chrome?

**Comment by visore** [comment] 2015-08-11 05:46
I've noticed that the issue happens more often if you are not on a new line, but appending to a current one. 

Here is what I did: Open Android Chrome -> go to Quill's website -> Click next to the last letter "r" in the heading inside the editor (Quill Rich Text Editor) -> Select bold, italics and underline -> type something.

In my case, bold and italics get automatically unselected. Underline stays active, but the underline is never actually applied to the text that you type. Hence, the format stays exactly the same as before. Other formats (eg: color, font, etc) have the same issue.

**Comment by jhchen** [comment] 2015-08-13 21:38
There appears to be two separate issues from my observations: 

1. Toolbar formatting on Android + Firefox is just messed up in general.
2. Android autocomplete is interfering with formatting on Chrome + Android browser.

Everything seems to be working as expected if the Android's autocomplete is not active (on a new line or after a space). Can you confirm this?

**Comment by visore** [comment] 2015-08-15 14:55
Yip, has mainly to do with autocomplete. When switched off, the problems disappear.

**Comment by jhchen** [comment] 2016-08-04 03:41
This looks like it is fixed in the [1.0 beta](http://beta.quilljs.com).

**Closed by jhchen** 2016-08-04 03:41 UTC
Labels: andriod, bug
