### ISSUE TITLE
Scroll position jumps when editor is inside of wrapper div

### ISSUE THREAD

**Issue by zokioki** [quilljs/quill#2166] opened 2018-06-22 20:32 UTC
Currently working on a project using Quill where we would like to have the toolbar be sticky as the user scrolls down the page (this provides a great experience for editing longer articles on both mobile and desktop).

The issue we've run into is that if the editor is wrapped inside another div, the scroll position jumps when editing the content, no matter how we configure the `scrollingContainer`:

![quill-sticky-toolbar-example](https://user-images.githubusercontent.com/5072525/41795086-6c37bb34-7616-11e8-8455-fb11eafc7625.gif)

**Steps for Reproduction**

> The following pens were branched off the [Auto-grow height example](https://codepen.io/quill/pen/dOqrVm) from Quill's playground

- Setting scrollingContainer to a dedicated `#scrolling-container` element:
  - Visit https://codepen.io/coxandrew/pen/pKKvNj
  - Scroll down to the "Scroll down below this header" header
  - Select some text and make it a link
  - After you click "save", the scroll position will jump all the way to the top

- Setting scrollingContainer to `html`:
  - Visit https://codepen.io/coxandrew/pen/qKYGJW
  - Scroll down to the "Scroll down below this header" header
  - Press enter multiple times, scroll position will jump down each time

- Works fine when editor is not wrapped inside a div:
  - https://codepen.io/coxandrew/pen/bKKbjr

**Expected behavior**:

Expected to not cause scroll position to jump when editor is inside a wrapper div and edits are performed.

**Actual behavior**:

Scroll position jumps up when `scrollingContainer` is set to a dedicated element, and down when set to `html`.

**Platforms**:

| Browser | Operating System |
| ------- | ---------------- |
| Chrome 67.0.3396.87 (_Official Build - 64-bit_) | macOS 10.13.5 (_High Sierra_) |

**Version**:

1.3.6

**Comment by zokioki** [comment] 2018-06-22 20:34
CC @coxandrew

**Comment by wmdmark** [comment] 2018-08-13 21:09
Bump... I have the same issue. Any work-arounds for this?

**Comment by RyanV** [comment] 2018-08-14 03:47
I can't reproduce this with the scrollingContainer set to `html`.  It seems to function as expected.  

tested with your codepen + Chrome Version 68.0.3440.106

**Comment by goggalore** [comment] 2019-06-26 17:11
Yep, still experiencing this in 2019. Only happens when the editor is contained in a wrapper. Guess the workaround is not to use a wrapper, though this limits the ability to use something like a flexbox to contain the editor and toolbar, for example.
Any updates?

**Comment by li2go** [comment] 2019-08-01 08:27
> Currently working on a project using Quill where we would like to have the toolbar be sticky as the user scrolls down the page (this provides a great experience for editing longer articles on both mobile and desktop).
> 
> The issue we've run into is that if the editor is wrapped inside another div, the scroll position jumps when editing the content, no matter how we configure the `scrollingContainer`:
> 
> ![quill-sticky-toolbar-example](https://user-images.githubusercontent.com/5072525/41795086-6c37bb34-7616-11e8-8455-fb11eafc7625.gif)
> 
> **Steps for Reproduction**
> 
> > The following pens were branched off the [Auto-grow height example](https://codepen.io/quill/pen/dOqrVm) from Quill's playground
> 
> * Setting scrollingContainer to a dedicated `#scrolling-container` element:
>   
>   * Visit https://codepen.io/coxandrew/pen/pKKvNj
>   * Scroll down to the "Scroll down below this header" header
>   * Select some text and make it a link
>   * After you click "save", the scroll position will jump all the way to the top
> * Setting scrollingContainer to `html`:
>   
>   * Visit https://codepen.io/coxandrew/pen/qKYGJW
>   * Scroll down to the "Scroll down below this header" header
>   * Press enter multiple times, scroll position will jump down each time
> * Works fine when editor is not wrapped inside a div:
>   
>   * https://codepen.io/coxandrew/pen/bKKbjr
> 
> **Expected behavior**:
> 
> Expected to not cause scroll position to jump when editor is inside a wrapper div and edits are performed.
> 
> **Actual behavior**:
> 
> Scroll position jumps up when `scrollingContainer` is set to a dedicated element, and down when set to `html`.
> 
> **Platforms**:
> 
> Browser	Operating System
> Chrome 67.0.3396.87 (_Official Build - 64-bit_)	macOS 10.13.5 (_High Sierra_)
> **Version**:
> 
> 1.3.6

i have same problem

**Comment by vinitpradhn18** [comment] 2019-08-14 09:58
Does anyone have a fix for this, yet?

**Comment by ImLuckyJr** [comment] 2019-08-14 13:21
You can try it https://stackoverflow.com/a/45823484

**Comment by itsmhuang** [comment] 2019-10-22 18:50
Having this issue as well. Setting scrollingContainer to `html` or wrapping div behaves the same: scroll jumps to top and back down.

**Comment by Doidel** [comment] 2019-12-31 20:43
I have the same issue. Any updates?

**Comment by tsalmeida** [comment] 2020-01-07 22:45
For anyone looking for a solution, I got it fixed by setting scrollingContainer to 'html'. My problem was caused by setting the toolbar to 'position: sticky', so that it would be always visible.

**Comment by edwardcahyadi** [comment] 2020-01-14 10:22
Facing the same issue, not being able to wrap the editor in a div is a big deal imo...

**Comment by Doidel** [comment] 2020-01-14 10:45
But you can. [The workaround on StackOverflow](https://stackoverflow.com/a/45823484) posted by ImLuckyJr helped me:
`componentDidMount()
{
$('.quill-toolbar').on("mousedown", function(event){
            event.preventDefault();
            event.stopPropagation();
        });
}`

**Comment by nazarposhta** [comment] 2020-09-08 11:53
@Doidel looks like it works

**Comment by TristanJanicki** [comment] 2021-04-08 16:56
If anyone is looking for a fix for this you can record the last selection range before your action that causes the scroll and then do `quill.setSelection(index, length)` and that fixes it (except the scroll is slightly off as it makes the selected text be the bottom of the scroll not say the middle)

**Comment by yasiinakbulut58** [comment] 2021-12-20 14:22
> But you can. [The workaround on StackOverflow](https://stackoverflow.com/a/45823484) posted by ImLuckyJr helped me:
> 
> > componentDidMount()
> > {
> > $('.quill-toolbar').on("mousedown", function(event){
> > event.preventDefault();
> > event.stopPropagation();
> > });
> > }

this works but not for ql-tooltip (link, video, image..)

**Comment by akkayaburak** [comment] 2023-07-13 09:56
> this works but not for ql-tooltip (link, video, image..)

Same here.

**Closed** 2023-08-01 14:45 UTC
