### ISSUE TITLE
Numbered list splits when removing middle element

### ISSUE THREAD

**Issue by iamdevelopin** [quilljs/quill#793] opened 2016-07-13 17:55 UTC
If you create a numbered list with 3 different items, then delete the middle item, the top and bottom item both become "1.", instead of "1." and then "2."

**Steps for Reproduction**

1. Visit quilljs.com
2. Empty the example on the home page
3. Click to make a numbered list
4. Enter "Element 1" and press return
5. Enter "Element 2" and press return
6. Enter "Element 3" and press return
7. Click at the end of the line of "Element 2" and press backspace until the line has been entirely removed

**Expected behavior**:
The elements left should be:-
1. Element 1
2. Element 3

**Actual behavior**:
The elements left are:-
1. Element 1
1. Element 3

**Platforms**:
Firefox 47 on OS X Yosemite

**Version**: 
0.20.1

**Comment by sachinrekhi** [comment] 2016-07-13 19:49
This is fixed in the upcoming Quill 1.0 release, which you can test here: http://beta.quilljs.com

**Comment by jhchen** [comment] 2016-07-14 18:41
Yup beta correctly merges the two lists.

**Closed by jhchen** 2016-07-14 18:41 UTC

**Comment by neandrake** [comment] 2016-09-07 00:41
I've only been trying out the demo available on the primary landing page, but this doesn't appear to be working correctly when using Backspace to delete middle items. It does work when using Delete. I'm using Firefox 48.0.1 on OSX 10.11.6.

My steps are:
1. From demo on http://quilljs.com/, remove all content
2. Add an Ordered list item
3. Add 3 items to the list
4. Remove content of item 2 so it is empty
  1. Use Backspace (on mac just "delete"), which should remove content prior to the cursor, or
  2. Use Delete (on macbook, "fn" + "delete"), which should remove after the cursor

**Comment by jhchen** [comment] 2016-09-07 07:06
@neandrake Looks like there was a regression. Should be fixed now on quilljs.com

**Comment by neandrake** [comment] 2016-09-07 23:35
Awesome, thank you!
