### ISSUE TITLE
Presing enter at the bottom of the editor will cause the whole page to scroll to top

### ISSUE THREAD

**Issue by Predjo** [quilljs/quill#544] opened 2015-12-09 12:33 UTC
How to reproduce:

1. Go to demo page: http://quilljs.com/
2. Scroll the whole page a little
3. At the bottom of the editor add a few new lines by pressing enter
4. The whole page will scroll to top

Tested in Chrome

**Comment by johann-abraham** [comment] 2016-04-06 14:25
+1

**Comment by duncanmeech** [comment] 2016-04-12 12:13
caused by scrollIntoView being called. I had to fork and patch for the same reason. Not sure of correct fix yet.

**Comment by jhchen** [comment] 2016-05-04 07:14
This has been fixed in the [beta](http://beta.quilljs.com/) release

**Closed by jhchen** 2016-05-04 07:14 UTC
Labels: bug, fixed-in-1.0
