### ISSUE TITLE
Add a source-code button

### ISSUE THREAD

**Issue by winterstein** [quilljs/quill#350] opened 2015-04-24 12:35 UTC
Feature request for a button to view and edit the html source code.

This would quickly provide support (albeit for advanced users only) for more complex mark-up -- such as tables, images, and layouts.

That would allow Quill to be used where such features are not often accessed, but must be editable if need be.

**Comment by jhchen** [comment] 2015-04-24 20:30
Duplicate of #128

**Closed by jhchen** 2015-04-24 20:30 UTC

**Comment by izzygld** [comment] 2019-01-09 14:10
Here is a component i made for Quill showing a "Source" show Html option to the Wysiwyg. 
See - https://gist.github.com/izzygld/0762dce7292baf2168f9c7b2aa99b535

**Comment by atilkan** [comment] 2019-03-07 22:18
@izzygld add left:0;

**Comment by benwinding** [comment] 2019-11-01 07:22
Well this was still an issue 3 years later.

So I made a little module to accomplish this.

https://github.com/benwinding/quill-html-edit-button

Demo

![Gd5Pc6U](https://user-images.githubusercontent.com/11782590/68008913-56baf180-fcd0-11e9-8449-fc8a0994519a.gif)

**Comment by CollinHerber** [comment] 2019-12-14 20:51
> Well this was still an issue 4 years later.
> 
> So I made a little module to accomplish this.
> 
> https://github.com/benwinding/quill-html-edit-button
> 
> Demo
> 
> ![Gd5Pc6U](https://user-images.githubusercontent.com/11782590/68008913-56baf180-fcd0-11e9-8449-fc8a0994519a.gif)

THANK YOU!@!1212312#!@#!@#
