### ISSUE TITLE
Request: Enable clean isomorphic/SSR

### ISSUE THREAD

**Issue by tashburn** [quilljs/quill#1905] opened 2018-01-08 19:49 UTC
It seems, based on these --

https://github.com/zenoamaro/react-quill/issues/185
https://github.com/zenoamaro/react-quill/issues/122

that it's a pain to do isomorphic server-side-rendering because the Quill library relies heavily on DOM APIs. The workaround (rendering different content server-side and client-side) is poor because React spits warnings about the div content not being the same.

A solution could be to not rely on the DOM APIs. Is this possible? I know the Slate Rich Text Editor can do SSR transparently.

**Comment by theskillwithin** [comment] 2018-01-10 18:57
+1

**Comment by DmitrySkripkin** [comment] 2018-01-11 10:21
I think it's related to #993 
Quill doesn't have any built-in tool to render delta without DOM APIs. You can try some third-party repos. 
Personally I failed with it, there is a difference in HTML + custom formats and blots are pain.
It's the big missing part in Quill :-1:

**Comment by benjismith** [comment] 2018-01-15 20:13
100% agree that this is the big missing piece of Quill...

I ended up having to write my own renderers from scratch, because the JSDom solution was too slow for my needs, and the third-party renderers are all broken in different ways.

**Comment by benbro** [comment] 2018-01-17 06:43
Duplicate of https://github.com/quilljs/quill/issues/993

**Closed by benbro** 2018-01-17 06:43 UTC

**Comment by jhchen** [comment] 2018-01-18 09:20
Also want to point out this is on the [2.0 Roadmap](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9#7c66)

**Comment by tashburn** [comment] 2018-01-18 19:56
Any sense when 2.0 comes out?

**Comment by goofballLogic** [comment] 2018-11-01 15:46
This will be awesome. Having to work around it for now.
