### ISSUE TITLE
Why does Quill add a <p><br></p> to the contents at init?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [quilljs/quill#1516] opened 2017-06-15 12:23 UTC
This, here.

    let contents = this.clipboard.convert(`<div class='ql-editor' style="white-space: normal;">${html}<p><br></p></div>`);

https://github.com/quilljs/quill/blob/fba09b116146f7403c9be6ccfabf3d08a83f1acb/core/quill.js#L101

Why does it do that? Can we change it to being optional? I'm making a single-line editor for h1:s etc.

**Comment by bjorn-ali-goransson** [comment] 2017-06-15 12:24
Also, I guess that the `<p>` should really be the configured block level element, right?

**Comment by DmitrySkripkin** [comment] 2017-06-20 09:00
You can see explanation here https://github.com/quilljs/quill/issues/1235#issuecomment-273044116 .

It's a bit tricky to make Quill single line, I didn't find any good example. I'd rather try plain contenteditable for such cases.

**Comment by jhchen** [comment] 2017-06-21 01:41
Thanks for the flag @DmitrySkripkin this is a dupe of #1235. Please read the [Contributing](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md) guidelines before creating another issue.

**Closed by jhchen** 2017-06-21 01:41 UTC
Labels: duplicate

**Comment by bjorn-ali-goransson** [comment] 2017-06-21 10:49
Well what about being able to customize the block tag name?

Den 21 jun 2017 03:41 skrev "Jason Chen" <notifications@github.com>:

**Comment by bjorn-ali-goransson** [comment] 2017-07-20 18:27
@DmitrySkripkin , I'd love to make my own solution but I have a hard time finding what exactly Quill does that prevents the input. It seems not so straight forward.

Additionally, I think Quill fixes some cross-browser quirks with hacks which are required when using the ContentEditable as canvas.

Care to chip in?

**Comment by bologer** [comment] 2018-10-06 07:01
@bjorn-ali-goransson use [this](https://github.com/quilljs/quill/issues/163#issuecomment-427551866)
