### ISSUE TITLE
Accepting spellcheck suggestion deletes containing span

### ISSUE THREAD

**Issue by szhu** [quilljs/quill#2527] opened 2019-02-28 22:34 UTC
This bug is rather specific but definitely reproducible and does happen in practice.

**Steps for Reproduction**

GIF of this happening:
![screen recording 2019-02-28 at 02 31 pm](https://user-images.githubusercontent.com/1570168/53603321-fdf5f080-3b65-11e9-92f5-8cb7799661d0.gif)

0. Use Chrome.
1. Create a new Google doc: https://docs.new
2. Type in `Sentence wthi a typo`. Copy the sentence.
3. Visit https://quilljs.com
4. Paste.
5. Wait for `wthi` to get a red underline. Then click it and accept the suggestion.

**Expected behavior**:
The suggestion should be selected.

**Actual behavior**:
The entire sentence is deleted. In the console:

```
addRange(): The given range isn't in document.
value @ selection.js:294
(anonymous) @ selection.js:48
o.emit @ index.js:151
value @ emitter.js:29
value @ scroll.js:162
(anonymous) @ scroll.ts:29
```

**Platforms**:
macOS Mojave, Chrome Version 73.0.3683.46 (Official Build) beta (64-bit)

**Version**:
1.3.6

**Comment by szhu** [comment] 2019-03-06 19:35
I think I've narrowed down the issue. This is the more general case that always fails:

0. Use Chrome.
1. In Quill, add some text that meets these properties:
   - Has a `span`
   - Has a typo somewhere inside the `span`.
2. Accepting the spellcheck will delete the entire span.

**Comment by Amit-Gore** [comment] 2019-08-13 07:15
I am facing the same problem while working with vue2-editor (quill based) 

`quill.formatText(offset, length, {
'color': 'red'
})`
Do you have any updates @szhu , did you manage to solve it ?

**Comment by szhu** [comment] 2019-08-13 08:10
We actually did, but it's kind of hacky -- basically we "unwrapped" the spans (replaced the spans with their children). Two key observations:
1. This will remove the styling that's set directly on the spans. For example, if you copy yellow text from Google Docs and use this fix, then the text will not be yellow anymore.
2. A way to make this process involve as little manual DOM manipulation as possible is to simply clear the `style` attribute from the spans. Quill will automatically "unwrap" useless spans!


Here's our rough pseudocode:

1. Listen for the the `text-change` event where the source is `user` (to prevent a feedback loop).

2. Find all the spans that you're okay removing all styles from. Specifically, to solve just the Google Docs example above and to not do anything too aggressive, we used:

   ```js
   quillContainer.querySelectorAll('span[style="background-color: transparent; color: rgb(0, 0, 0);"]')
   ```

   But you can select all spans if you want.

3. For each of these results, clear their style attribute, i.e., `element.removeAttribute("style")`.

**Comment by ruchira088** [comment] 2020-07-06 01:18
Any updates on this issue?

**Comment by maniyadv** [comment] 2020-09-24 11:26
I got this solved by formatting the pasted content to plaintext before spell check using -

```javascript
quill.clipboard.addMatcher (Node.ELEMENT_NODE, function (node, delta) {
    var plaintext = node.innerText
    var Delta = Quill.import('delta')
    return new Delta().insert(plaintext)
})
```

Or use - [https://www.npmjs.com/package/quill-paste-smart](https://www.npmjs.com/package/quill-paste-smart)

**Comment by Nicholas-Westley** [comment] 2020-10-22 13:04
Is there any update on this?  Any idea where I would have to start looking in the quill codebase if I wanted to fix it?

**Comment by denishegarty** [comment] 2021-01-16 15:47
Is there any update on this?

**Comment by sho13** [comment] 2021-02-26 16:26
Hello, are there any updates on this?

**Comment by RyanLackie** [comment] 2021-02-26 16:27
Hello, are there any updates on this?

**Comment by RyanLackie** [comment] 2021-02-26 16:28
Hi, are there any updates on this bug?

**Comment by njtmead** [comment] 2021-04-10 06:21
+1

**Comment by kenichi-ando** [comment] 2021-06-15 01:55
This seems to be a duplicate of https://github.com/quilljs/quill/issues/2096.

**Comment by luin** [comment] 2023-07-30 06:02
👋 Sorry for the late update. This is fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing.

**Closed by luin** 2023-07-30 06:02 UTC

**Comment by kenichi-ando** [comment] 2023-07-31 04:46
@luin Do you have any plans to release the new version including this fix?
