### ISSUE TITLE
how to insert recorded video into quill editor

### ISSUE THREAD

**Issue by vibingopal** [quilljs/quill#2059] opened 2018-04-07 13:02 UTC
Hello Team,

In my application, iam using quill editor with Angular framework. Now i have customized the tool bar so that users can record the video, once the recording ended. iam trying to insert the recorded video ( video/webm) format into the quill editor. 

But the problem is the video is not playable. I can only see in the quill editor the url of the video which is of blob type like blob:http://localhost:4100/b37bfaef-2a78-4a55-ad3d-15a1bb28d83

When i open the same url in browser it is getting played but not in editor. Any suggestions on this? Do i need to convert the video of webm to different format to get played in quill editor ?

**Comment by vibingopal** [comment] 2018-04-08 14:17
this is my end output in editor contents 

Assigned video to editor 
this.editorContent = temp1;
this.editorContent = temp1;
console.log('Editor Content', this.editorContent);
Output:
<video src="blob:http://localhost:4100/98a2a2fe-6d74-4cfe-bc5b-96ff8493c18" controls="controls" autoplay="" width="320" height="240"></video>

**Comment by vibingopal** [comment] 2018-04-09 14:27
May i have any update on this please?

**Comment by benbro** [comment] 2018-04-09 14:32
You'll might get more help if you fork the [playground example](https://quilljs.com/playground/) and show a simple example of what you are trying to do and what doesn't work.

**Comment by vibingopal** [comment] 2018-04-09 15:04
Iam trying to insert the blob video into quill editor. Here the video is recorder through different tool which is recordrtc. Once the recording stopped , iam assigning the blob url to video element and appending the quill contents as shown above.

**Comment by benbro** [comment] 2018-04-09 16:12
That's more of a question to StackOverflow or a job for a custom module.
Closing because it's not a bug.

**Closed by benbro** 2018-04-09 16:12 UTC

**Comment by lakinmohapatra** [comment] 2018-08-30 17:45
Hi 
I am assigning video html to editor like this 
this.editor = '<video controls="" class="ql-video" width="100%" height="100%" player-source="http://localhost:8080/media/7dd839e1f7989dbb.mp4"><source src="blob:http://localhost:8080/media/7dd839e1f7989dbb.mp4" type="video/mp4"></video>';

But its showing blank in QL UI. Please help.

**Comment by muralimatli** [comment] 2019-06-19 04:13
am unable to insert recorded mp4/mp3 videos into quill editor
