### ISSUE TITLE
Faulty behavior with short texts in Chrome when toggling UL/OL

### ISSUE THREAD

**Issue by CC84** [quilljs/quill#694] opened 2016-05-24 07:37 UTC
I'm new to quill and just tested some features. In my editor are only links and ul/ol allowed. In Chrome the editor often produces unexpected results.

**Steps for Reproduction**

1. Visit quilljs.com
2. Remove all the text
3. Enter:
asdf
asdf
asdf
Ensure cursor is in the last line.
4. Toggle ul/ol
5. After some tries not the last line is toggled, instead the editor changes the first line. In some cases you can go back to last line and change last line again, but there are also cases i wasn't able to change last line again. Everytime i set back the cursor, the just jumped back to first line and changed the first line.

**Expected behavior**: Cursor shouldn't jump, always currentline should be changed

**Actual behavior**: Sometime the firstline is changed, sometimes it's impossible to change last line again.

**Platforms**: Version 50.0.2661.102 m on Windows 10

**Version**: 0.20.1

This errors seems to be gone, when the box contains more text.

**Comment by jhchen** [comment] 2016-05-24 19:56
This is a duplicate of #487 and is fixed in [1.0](http://beta.quilljs.com). The inconsistency is due to whether or not the mouse moved between the down and up on a click.

**Closed by jhchen** 2016-05-24 19:56 UTC

**Comment by CC84** [comment] 2016-05-25 05:49
Bad news.... 1.0 doesn't seem to be downwards compatible, so at this state i can't change to 1.0. Furthermore 1.0 is at beta state. Wouldn't it possible to fix this in your last stable release?

**Comment by jhchen** [comment] 2016-05-25 07:30
The workaround described in #487 should work
