### ISSUE TITLE
Inline styling lost after loading/pasting html

### ISSUE THREAD

**Issue by drego** [quilljs/quill#1580] opened 2017-07-10 09:50 UTC
I'm currently trying to use Quill to create an editor and be able to format an email in HTML.
In order to allow the styling of the email content I'm using only inline styling attributes instead of the quill classes.
However, when I try to load or paste the html content into the editor, some of the inline styles are ignored/removed. I noticed that some of the inline styles (like color, background-color,text-align) are kept but others are just removed (for instance some font families and text-indent).
[Here](https://codepen.io/anon/pen/yXqPLE) is a verifiable example of this problem. 

**Steps for Reproduction**

1. Visit the [example](https://codepen.io/anon/pen/yXqPLE) provided
2. Verify that some inline fonts are applied by Quill and others are ignored.
3. Verify that the indent specified with inline styling is ignored by Quill.

**Expected behavior**:
 The fonts and indent specified by inline styling should be recognized and kept by Quill.

**Actual behavior**:
Some fonts are kept and others are removed when loading Quill. Text indent specified by inline styling is also removed.

**Platforms**:
Google Chrome Version 58.0.3029.110 (64-bit)

**Version**:
1.2.6

**Comment by revmischa** [comment] 2017-07-26 16:51
This is a high priority issue for us, we need the ability to initialize the editor with some pre-existing HTML with inline styling.

**Comment by sendlane-ray** [comment] 2017-08-18 19:36
Is there a workaround for this?

**Comment by revmischa** [comment] 2017-08-18 19:51
yeah switch to a different editor lmao

**Comment by sendlane-ray** [comment] 2017-08-23 17:42
Downgrade to version 1.0.3. (bug started with version 1.0.4)
or delete the whitelist. 

This bug only happens when the font family has quotes.

import Quill from 'quill';

let Font = Quill.import('attributors/style/font');
delete Font.whitelist;

Quill.register(Font);

**Comment by jhchen** [comment] 2018-01-22 07:48
This is fixed with the fix from #1873 https://github.com/quilljs/quill/commit/fa99fa09981248ebe502be5c0f188ba2c100b94a for font family. The expected case for text indent is replace with a tab character, which it already does.

**Closed by jhchen** 2018-01-22 07:48 UTC
Labels: bug

**Comment by dynothunder** [comment] 2018-05-31 12:59
The expected case for text indent is replace with a tab character, which it already does. can't understand where you told about tab character

**Comment by pdkovacs** [comment] 2019-05-23 15:38
I am strill having this issue with version 1.3.6 with code based on this example: https://stackoverflow.com/questions/43728080/how-to-add-font-types-on-quill-js-with-toolbar-options (And the issue is -- still -- with font families having white space(s) included in their names.)

The key difference compared with the test code here is how the font "module" is imported:
`formats/font` vs `attributors/style/font` .
Is one of them incorrect? Are they both correct, just serving different purpose?

**Comment by MwumLi** [comment] 2019-11-29 12:35
how to solve this?

**Comment by bogoroh** [comment] 2020-12-30 02:18
@drego, Did you fix this? Still having the issue

**Comment by komendantaa** [comment] 2023-11-07 20:23
I've found a workaround. 
`  editorCreated(quill: Quill) {
    quill.clipboard.addMatcher(Node.ELEMENT_NODE, function (node, delta) {
      const font = node.className.match(/(?<=ql-font-)(\w*-?)*/)?.[0];
      if (font) {
        return new Delta().insert(node.textContent, {
          ...(delta?.ops?.[0].attributes ?? {}),
          font: font,
        })
      }
      return delta
    })
    this.content = this._content;
  }
  `
  Worked for me.
