### ISSUE TITLE
:first-letter styling breaks Quill's behaviour

### ISSUE THREAD

**Issue by yukulelix** [quilljs/quill#1823] opened 2017-11-17 13:02 UTC
Hi there,

Quill's behaviour seems to be broken when styling paragraphs with `:first-letter` in CSS

I made this little Codepen experiment based on the playground

**Steps for Reproduction**
1. Go to https://codepen.io/yukulelix/pen/YEEvXa
2. Try to delete a character in one of the lines

**Expected behavior**:
It should delete only one character

**Actual behavior**:
It deletes the whole line

**Platforms**:
Chrome 62.0.3202.94
MacOs High Sierra 10.13.1

**Version**:
Quill 1.3.4

**Comment by benbro** [comment] 2017-11-18 20:56
I can reproduce with Chrome on Windows 7.
Works fine in Firefox 57.

**Comment by yorrd** [comment] 2017-12-20 18:17
Confirming on Linux, Firefox works fine, Chrome does not. Latest Quill Version

**Comment by jacwright** [comment] 2018-04-05 20:40
This is an issue with the browser and you'll find the same issue in other editors. I'm not sure if there is a solution to work around this, but the issue isn't with Quill itself. See this fork without quill, same issue: https://codepen.io/jacwright/pen/YaJZPE. I would recommend closing this or marking it as a feature request (to come up with a workaround if possible) rather than a bug.

**Comment by jhchen** [comment] 2018-04-16 04:17
Thanks for digging in @jacwright. Quill does try to patch some broken browser behavior but since first-letter styling is not a common use in my experience this is not a priority bug. I will close as suggested so people are not waiting/expecting a fix as it's quite unlikely given the priority and volume of other tasks.

**Closed by jhchen** 2018-04-16 04:17 UTC
Labels: bug
