### ISSUE TITLE
Quill couldn't recognize the first row when use Chinese input

### ISSUE THREAD

**Issue by Leo555** [quilljs/quill#1541] opened 2017-06-23 09:01 UTC
[Describe the issue]

Quill couldn't recognize the first row when use Chinese input, and the trigger conditions are: chrome version is 49/51/53/54 and os is win10 and Chinese input.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Input anything by using Chinese input
3. Enter and then Back. 
4. The first line is ignored by quill editor.

**Expected behavior**:

**Actual behavior**:
![](https://ooo.0o0.ooo/2017/06/23/594cd72fe31e6.gif)

**Platforms**:
os: win10
browser: chrome 49/51/53/54
input: Sogou Pinyin 8.4

chrome version greater than 55 is ok, and win7 is ok, and other input is ok.

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by jhchen** [comment] 2017-07-17 04:39
This looks like a duplicate of #849 so try disabling all Chrome extensions. Also Quill only supports the latest two versions of Chrome so 55 is no longer supported.

**Closed by jhchen** 2017-07-17 04:39 UTC
