### ISSUE TITLE
Shadow DOM support - continued

### ISSUE THREAD

**Issue by yananym** [quilljs/quill#2961] opened 2020-03-10 00:23 UTC
Follow up of issues https://github.com/quilljs/quill/issues/2021 and https://github.com/quilljs/quill/issues/1472 to add support for Shadow DOM.

More and more apps are being built with Micro Front End architecture in mind, which means components including editor experience are delivered through as a web component, which means, Shadow DOM. 

Cisco had been leveraging quill in Contact Center cloud enterprise solution, and now is moving to MFE architecture. 

I will be opening a simple PR on behalf of Cisco to address it, please let me know if quill team would have bandwidth to review it within the next 3-4 months, it would help greatly!

**Comment by mike-shtil** [comment] 2020-03-11 15:12
@yananym all power to you. It's a shame this Shadow DOM supporting implementation wasn't merged before becoming stale: https://github.com/web-padawan/quill
But I'm sure something similar can be created for Quill 2.x.x

**Comment by albert-sf** [comment] 2020-03-23 20:51
Any update on this PR?

**Comment by aanavaneeth** [comment] 2020-03-27 18:50
Any update on this? I think as a community we must encourage the web component standard and we cannot be a bottle neck.

**Comment by kr05** [comment] 2020-04-03 02:30
I'm glad to see a relatively new issue addressing shadow DOM support. I'd be happy to help in any way. Will integrating the changes from https://github.com/web-padawan/quill into a fresh fork of quill be useful?

**Comment by yananym** [comment] 2020-04-03 02:34
This is actually exactly what one of my engineers had done. He had reported that some Jasmine unit tests are failing and he was not able to resole them, i had not been able to find time to look into it as of yet. @kr05 Kevin would you be able to take a look at tests failures? i would be grateful! 
https://github.com/yananym/quill

**Comment by kr05** [comment] 2020-04-03 02:49
Of course, I'll see what I can do!

**Comment by quangnotes** [comment] 2020-04-03 04:02
@yananym it still not work on Safari (my safari version: 13.1). But it's work on Chrome & Firefox, although I see some errors on the console

**Comment by quangnotes** [comment] 2020-04-03 04:34
@yananym it still not work on Safari (my safari version: 13.1). But it's work on Chrome & Firfox

**Comment by kr05** [comment] 2020-04-03 04:49
Has anyone tried setting up the dev environment on WSL? I'm getting some issues with installing nokogiri. I'll keep trying, but if anyone has any suggestions I would appreciate it. I can provide more info as requested.

![error 1](https://user-images.githubusercontent.com/11833744/78325175-c5280800-752b-11ea-861a-13f677ade2cf.png)
![error 2](https://user-images.githubusercontent.com/11833744/78325181-c6f1cb80-752b-11ea-958e-ac0f469ca28b.png)

**Comment by albert-sf** [comment] 2020-04-08 16:31
I try the https://github.com/yananym/quill, I didn't see issue on mac.

**Comment by turboMaCk** [comment] 2021-02-22 15:20
@kr05 I think the error is realtively clear. you'll need to install pkg-config (program that helps C compiler discover libraries to link - it essentially generates -l* falgs to cc). You might also need to install libxml2 and other dependencies. Last time I used windows was 10 years ago so I can't provide more specific help but perhaps you can just `apt-get install` it in WSL?

I'm also interested seeing some progress here. Shadow dom support is not a deal breaker for me but I would still rather use the shadow if I could. Is anyone working on this at the moment? And if not are PRs implementing this accepted?

**Comment by turboMaCk** [comment] 2021-02-22 15:35
@kr05 actually I think you find answers to your questions in this post https://davemateer.com/2020/10/20/running-jekyll-on-wsl2

**Comment by dman777** [comment] 2021-03-04 20:23
Any updates on this? I am using react-quill in shadow dom and I have strange issues with it.

**Comment by turboMaCk** [comment] 2021-03-04 20:40
@dman777 yes that's what I also experienced just with my hand-coded web-component embedded in elm application. For time being I would recommend you to abandon shadow DOM and just namespace things as best as you can. It seems to me that quill depends on some of the global stuff (event handlers on window and such) to work properly. Luckily these things are not a major problem if you're careful™. The limitation is probably the biggest problem for folks who need to integrate quill to code that itself is used in shadow dom like the micro frontend oriented apps. It seems there is no interest in maintainers on this so the options seems to be either to fork quill or to live with it as is.

**Comment by yujiri8** [comment] 2021-03-09 07:13
I'm another person who wants to use Quill but needs it inside a web component context. I can get Quill to import and render and it kind of works, but the issue preventing me from using it is that it can get into a state where every keypress sends the cursor back to the start and inserts a newline, so trying to type a word will produce each character on its own line and in reverse order. Clicking inside the text box while it's empty toggles this state somewhat reliably.

It only happens when it's inside a web component, but that's my only lead.

**Comment by turboMaCk** [comment] 2021-03-09 07:57
@yujiri8 isn't it possible that you have quill in some vdom based FW (like React) and that every keypress causes react to render Quill again (insert after v dom diff) so the problem is not the quill itself but the fact you initialize it again after every key?

I'm 100% certain it's possible to embed quill as web-component (without shadow DOM). I think the problem is somewhere in your approach.

**Comment by yujiri8** [comment] 2021-03-09 14:52
The FW I'm using is Lit-Element. It only re-renders a component when
an attribute changes, so keypresses should not trigger that.

**Comment by turboMaCk** [comment] 2021-03-09 16:28
This is the vanila JS (ES2015) custom elment wrapper that works:

```js
const toolbarOptions = [
  [{ 'header': [1, 2, false] }],
  ['bold', 'underline', 'italic', 'strike'],        // toggled buttons
  [{ 'background': [] }, { 'color': [] }],          // dropdown with defaults from theme
  [{ 'script': 'super' }, { 'script': 'sub'}],      // superscript/subscript
  [{ 'list': 'bullet' }, { 'list': 'ordered'}],
  [{ 'indent': '+1'}, { 'indent': '-1' }],          // outdent/indent

  ['code-block', 'blockquote'],
  ['clean']                                         // remove formatting button
];


class MyQuill extends HTMLElement {
  constructor() {
    // Always call super first in constructor
    super();

    // Setup container
    this.editorContainer = document.createElement('div');
  }

  connectedCallback() {
    this.prepend(this.editorContainer);

    const quill = new Quill(this.editorContainer, {
      modules: {
        toolbar: toolbarOptions
      },
      theme: 'snow' // or 'bubble'
    });
    this._quill = quill;
  }
}

customElements.define("my-quill", MyQuill);
```

**Comment by yujiri8** [comment] 2021-03-09 19:35
> as I said:
> 
> > web-component (**without shadow DOM**).

Oh, I missed that part of your reply. But yes I need it inside shadow DOM. And that is the title of this issue, after all.

**Comment by artemiusgreat** [comment] 2021-06-10 04:10
In this example, editor is created inside Shadow Root. 
[](https://codepen.io/artemiusgreat/pen/XWMPdWG)
The main concern so far is that inline formatting doesn't work when initiated from Toolbar module by clicking `Bold` or `Italic` buttons on the panel. 
The reason is that `window.getSelection` always returns empty selection inside the Shadow Root. 
The good thing is that it somehow works when inline formatting is initiated from Keyboard module by pressing `CTRL + B` or `CTRL + I`. 
I'm digging into the code, but if somebody already resolved this I would appreciate some guidance.

**Comment by artemiusgreat** [comment] 2021-06-11 23:25
Kind of fixed. 
[https://stackoverflow.com/a/67944380/437393](https://stackoverflow.com/a/67944380/437393)

**Comment by littleweb** [comment] 2021-06-18 09:34
> Kind of fixed.
> https://stackoverflow.com/a/67944380/437393

thank you very mush!

**Comment by robrez** [comment] 2022-01-07 05:02
Happy new year everyone.  Anyone else still eagerly awaiting some traction here?  Please feel free to provide some comments/thoughts on my branch - https://github.com/robrez/quill/pull/1

**Comment by littleweb** [comment] 2022-01-26 06:45
> @yananym all power to you. It's a shame this Shadow DOM supporting implementation wasn't merged before becoming stale: https://github.com/web-padawan/quill But I'm sure something similar can be created for Quill 2.x.x

parse not work.

**Comment by C0ncept95** [comment] 2022-07-26 14:12
> Kind of fixed. https://stackoverflow.com/a/67944380/437393

I noticed that copy-pasting text is not working with this approach, which can be observed [here](https://codepen.io/artemiusgreat/pen/XWMPdWG). Does anyone have a workaround for this?

**Comment by itamarzil123** [comment] 2022-11-01 11:00
We are also using Quill and WebComponents ( Lit Element ) as part of our rich / fully featured text editor.
We are currently still suffering from the fact Selection API doesn't understand the shadow DOM in Safari / Firefox
this polyfil: https://github.com/GoogleChromeLabs/shadow-selection-polyfill together with this function:
https://stackoverflow.com/questions/67914657/quill-editor-inside-shadow-dom/67944380#67944380
**solved the issue on firefox** (the entire toolbar and selection of text and trying to apply the toolbar functionality on the selected text didn't work without this polyfil.
some issues were not resolved by the polyfil. 
for example: same issue of @yujiri8  https://github.com/quilljs/quill/issues/2961#issuecomment-793999566
-
HOWEVER - **the biggest problem is with Safari** -> not even one polyfil worked for us.
anyone knows what other companies that use LitElement and ShadowDOM with rich text editors do with Safari ?

**Comment by jhefferman-sfdc** [comment] 2023-10-23 20:51
In case anyone is still trying to solve this, here's what I have (seems to work ok in Chromium, Gecko, Webkit browsers, including copy/paste, selection, keyboard shortcuts, etc. All issues seemed to boil down to three problems:

1. Getting `Range`: `document.getSelection` doesn't work in Native Shadow and each browser has a different implementation (for getting ranges)
2. Checking Focus: `document.activeElement` needs to be replaced by `shadowRoot.activeElement`
3. Setting Range: `Selection.addRange` does not work in Safari in Native Shadow but can be replaced with `Selection.setBaseAndExtent`

Here's a codepen example: https://codepen.io/John-Hefferman/pen/yLZygKo?editors=1000
Here's the monkeypatch:
` // Check taken from the now defunct Google selection polyfill: https://github.com/GoogleChromeLabs/shadow-selection-polyfill/blob/master/shadow.js
    const hasShadowRootSelection = !!(document.createElement('div').attachShadow({ mode: 'open' }).getSelection);

    // Each browser engine has a different implementation for retrieving the Range
    const getNativeRange = (rootNode) => {
        try {
            if (hasShadowRootSelection) {
                // In Chromium, the shadow root has a getSelection function which returns the range
                return rootNode.getSelection().getRangeAt(0);
            } else {
                const selection = window.getSelection();
                if (selection.getComposedRanges) {
                    // Webkit range retrieval is done with getComposedRanges (see: https://bugs.webkit.org/show_bug.cgi?id=163921)
                    return selection.getComposedRanges(rootNode)[0];
                } else {
                    // Gecko implements the range API properly in Native Shadow: https://developer.mozilla.org/en-US/docs/Web/API/Selection/getRangeAt
                    return selection.getRangeAt(0);
                }
            }
        } catch {
            return null;
        }
    }

    /** 
     * Original implementation uses document.active element which does not work in Native Shadow.
     * Replace document.activeElement with shadowRoot.activeElement
     **/
    quill.selection.hasFocus = function () {
        const rootNode = quill.root.getRootNode();
        return rootNode.activeElement === quill.root;
    }

    /** 
     * Original implementation uses document.getSelection which does not work in Native Shadow. 
     * Replace document.getSelection with shadow dom equivalent (different for each browser)
     **/
    quill.selection.getNativeRange = function () {
        const rootNode = quill.root.getRootNode();
        const nativeRange = getNativeRange(rootNode);
        return !!nativeRange ? quill.selection.normalizeNative(nativeRange) : null;
    };

    /**
     * Original implementation relies on Selection.addRange to programatically set the range, which does not work
     * in Webkit with Native Shadow. Selection.addRange works fine in Chromium and Gecko.
     **/
    if (isSafari) {
        quill.selection.setNativeRange = function (startNode, startOffset) {
            var endNode = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : startNode;
            var endOffset = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : startOffset;
            var force = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : false;
            if (startNode != null && (quill.selection.root.parentNode == null || startNode.parentNode == null || endNode.parentNode == null)) {
                return;
            }
            var selection = document.getSelection();
            if (selection == null) return;
            if (startNode != null) {
                if (!quill.selection.hasFocus()) quill.selection.root.focus();
                var native = (quill.selection.getNativeRange() || {}).native;
                if (native == null || force || startNode !== native.startContainer || startOffset !== native.startOffset || endNode !== native.endContainer || endOffset !== native.endOffset) {
                    if (startNode.tagName == "BR") {
                        startOffset = [].indexOf.call(startNode.parentNode.childNodes, startNode);
                        startNode = startNode.parentNode;
                    }
                    if (endNode.tagName == "BR") {
                        endOffset = [].indexOf.call(endNode.parentNode.childNodes, endNode);
                        endNode = endNode.parentNode;
                    }
                    selection.setBaseAndExtent(startNode, startOffset, endNode, endOffset);
                }
            } else {
                selection.removeAllRanges();
                quill.selection.root.blur();
                document.body.focus();
            }
        }
    }

    /**
     * Subscribe to selection change separately, because emitter in Quill doesn't catch this event in Shadow DOM
     **/
    const handleSelectionChange = function () {
        quill.selection.update();
    };

    document.addEventListener("selectionchange", handleSelectionChange);`

**Comment by vialoh** [comment] 2023-10-25 09:42
@jhefferman-sfdc Thank you for this! I went in circles for hours trying to find a fix for this and finally found your comment, and you wrote it only a couple days ago! Great timing. Thanks again.

**Comment by turboMaCk** [comment] 2023-10-25 09:52
I wonder if this solution can't be turned into patch that could get accepted. cc @dlitsman how do you feel about @jhefferman-sfdc's solution?

**Comment by jhefferman-sfdc** [comment] 2023-10-25 23:05
If folks are generally OK with this approach, I'd be happy to rework it so it functions in Light DOM too and submit a PR for review? Let me know.

**Comment by Thilo84** [comment] 2023-12-20 13:02
@jhefferman-sfdc I'm very happy with your code. This fixed our problem too. Thanks a lot!

**Closed** 2024-04-17 11:20 UTC

**Comment by conceptree** [comment] 2025-02-28 15:04
Hello all, 

We started to use quilljs in our stencil js components library without imagining that shadow dom could be something that the library did not consider. This is still a problem with quill 2.0.3, being the case, shouldn't this ticket be reopened? 

Thanks in advance.

**Comment by algebrakit** [comment] 2025-07-05 20:05
See  [PR#4688](https://github.com/slab/quill/pull/4688) for shadow dom support
